// All 72 Caption Templates extracted from Captik (https://captik.in/templates)
// Pixel-accurate recreation with typography, 3D depth, cutout layers, and animations.
import type { CapStyle } from "./captionStyle";

const FONT_MAP: Record<string, string> = {
  "Inter": "'Inter', system-ui, sans-serif",
  "Poppins": "'Poppins', 'Inter', sans-serif",
  "Montserrat": "'Montserrat', 'Inter', sans-serif",
  "Space Grotesk": "'Space Grotesk', 'Inter', sans-serif",
  "DM Sans": "'DM Sans', 'Inter', sans-serif",
  "Outfit": "'Outfit', 'Inter', sans-serif",
  "Anton": "'Anton', 'Impact', sans-serif",
  "Archivo Black": "'Archivo Black', 'Impact', sans-serif",
  "Bebas Neue": "'Bebas Neue', 'Impact', sans-serif",
  "Bangers": "'Bangers', 'Impact', cursive",
  "Permanent Marker": "'Permanent Marker', cursive",
  "Press Start 2P": "'Press Start 2P', ui-monospace, monospace",
  "EB Garamond": "'EB Garamond', Georgia, serif",
  "Playfair Display": "'Playfair Display', Georgia, serif",
  "DM Serif Display": "'DM Serif Display', Georgia, serif",
  "Special Elite": "'Special Elite', ui-monospace, monospace",
  "Work Sans": "'Work Sans', 'Inter', sans-serif",
  "Oswald": "'Oswald', 'Impact', sans-serif",
  "Black Ops One": "'Black Ops One', 'Impact', sans-serif",
  "Plus Jakarta Sans": "'Plus Jakarta Sans', 'Inter', sans-serif",
};

const font = (label: string): string => FONT_MAP[label] ?? `'${label}', system-ui, sans-serif`;

export interface CaptikPresetItem {
  id: string;
  name: string;
  cleanName: string;
  category: "Behind you" | "Popular" | "Bold & animated" | "Clean" | "Property reels";
  isBehindYou: boolean;
  isNew: boolean;
  video: string;
  poster: string;
  patch: Partial<CapStyle>;
}

export const CAPTIK_72_PRESETS: CaptikPresetItem[] = [
  {
    id: "captik_glow",
    name: "Captik · Captik Glow",
    cleanName: "Captik Glow",
    category: "Popular",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/captik_glow.mp4",
    poster: "/previews/p/captik_glow.webp",
    patch: {
      fontFamily: font("Space Grotesk"),
      fontWeight: 800,
      fontSize: 48,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 95,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2.5,
      glowOn: true,
      glowColor: "#F59E0B",
      glowBlur: 18,
      glowIntensity: 90,
      activeWordOn: true,
      activeWordColor: "#FCD34D",
      activeWordScale: 1.18,
    }
  },
  {
    id: "ali_abdaal",
    name: "Captik · Ali Abdaal",
    cleanName: "Ali Abdaal",
    category: "Clean",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/ali_abdaal.mp4",
    poster: "/previews/p/ali_abdaal.webp",
    patch: {
      fontFamily: font("Inter"),
      fontWeight: 600,
      fontSize: 38,
      textCase: "normal",
      color: "#F8FAFC",
      posY: 82,
      wordsPerChunk: 3,
      transition: "fade",
      transitionSpeed: 150,
      bgOn: true,
      bgColor: "rgba(0, 0, 0, 0.75)",
      bgOpacity: 80,
      bgRadius: 8,
      bgPadX: 14,
      bgPadY: 6,
      activeWordOn: true,
      activeWordColor: "#38BDF8",
      activeWordScale: 1.05,
    }
  },
  {
    id: "captik_shadow",
    name: "Captik · Captik Shadow",
    cleanName: "Captik Shadow",
    category: "Popular",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/captik_shadow.mp4",
    poster: "/previews/p/captik_shadow.webp",
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 900,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 80,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 100,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 5,
      shadowBlur: 10,
      activeWordOn: true,
      activeWordColor: "#FACC15",
      activeWordScale: 1.15,
    }
  },
  {
    id: "captik",
    name: "Captik · Captik",
    cleanName: "Captik",
    category: "Popular",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/captik.mp4",
    poster: "/previews/p/captik.webp",
    patch: {
      fontFamily: font("Plus Jakarta Sans"),
      fontWeight: 800,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 79,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 85,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.16,
    }
  },
  {
    id: "clean_motion",
    name: "Captik · Clean Motion",
    cleanName: "Clean Motion",
    category: "Clean",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/clean_motion.mp4",
    poster: "/previews/p/clean_motion.webp",
    patch: {
      fontFamily: font("Inter"),
      fontWeight: 700,
      fontSize: 40,
      textCase: "normal",
      color: "#FFFFFF",
      posY: 82,
      wordsPerChunk: 3,
      transition: "slide-up",
      transitionSpeed: 140,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 60,
      shadowX: 0,
      shadowY: 2,
      shadowBlur: 6,
      activeWordOn: true,
      activeWordColor: "#E0E7FF",
      activeWordScale: 1.08,
    }
  },
  {
    id: "bubble",
    name: "Captik · Bubble Style",
    cleanName: "Bubble Style",
    category: "Bold & animated",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/bubble.mp4",
    poster: "/previews/p/bubble.webp",
    patch: {
      fontFamily: font("Bangers"),
      fontWeight: 800,
      fontSize: 52,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "bounce",
      transitionSpeed: 110,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 95,
      shadowX: 3,
      shadowY: 3,
      shadowBlur: 0,
      activeWordOn: true,
      activeWordColor: "#FFE600",
      activeWordScale: 1.25,
    }
  },
  {
    id: "hormozi",
    name: "Captik · Hormozi Style",
    cleanName: "Hormozi Style",
    category: "Popular",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/hormozi.mp4",
    poster: "/previews/p/hormozi.webp",
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 50,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 4.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 95,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 12,
      activeWordOn: true,
      activeWordColor: "#FFE600",
      activeWordScale: 1.25,
    }
  },
  {
    id: "boxed",
    name: "Captik · Editing Skool",
    cleanName: "Editing Skool",
    category: "Popular",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/boxed.mp4",
    poster: "/previews/p/boxed.webp",
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 900,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 95,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3,
      activeWordOn: true,
      activeWordColor: "#000000",
      activeWordScale: 1.15,
      activeWordBgOn: true,
      activeWordBgColor: "#00F0FF",
    }
  },
  {
    id: "mrbeast",
    name: "Captik · Mr Beast Style 1",
    cleanName: "Mr Beast Style 1",
    category: "Popular",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/mrbeast.mp4",
    poster: "/previews/p/mrbeast.webp",
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 52,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 76,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 85,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 4,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 10,
      activeWordOn: true,
      activeWordColor: "#FFE600",
      activeWordScale: 1.22,
      activeWordBgOn: true,
      activeWordBgColor: "#DC2626",
    }
  },
  {
    id: "mr_beast_2",
    name: "Captik · Mr Beast Style 2",
    cleanName: "Mr Beast Style 2",
    category: "Popular",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/mr_beast_2.mp4",
    poster: "/previews/p/mr_beast_2.webp",
    patch: {
      fontFamily: font("Archivo Black"),
      fontWeight: 900,
      fontSize: 50,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 76,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 4,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 10,
      activeWordOn: true,
      activeWordColor: "#22C55E",
      activeWordScale: 1.24,
    }
  },
  {
    id: "iman_gadzhi",
    name: "Captik · Iman Gadzhi",
    cleanName: "Iman Gadzhi",
    category: "Popular",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/iman_gadzhi.mp4",
    poster: "/previews/p/iman_gadzhi.webp",
    patch: {
      fontFamily: font("EB Garamond"),
      fontWeight: 700,
      fontSize: 42,
      textCase: "title",
      color: "#FFFBEB",
      posY: 82,
      wordsPerChunk: 3,
      transition: "fade",
      transitionSpeed: 180,
      glowOn: true,
      glowColor: "#D4AF37",
      glowBlur: 14,
      glowIntensity: 70,
      bgOn: true,
      bgColor: "rgba(15, 15, 20, 0.75)",
      bgOpacity: 80,
      bgRadius: 6,
      bgPadX: 16,
      bgPadY: 6,
      activeWordOn: true,
      activeWordColor: "#FCD34D",
      activeWordScale: 1.08,
    }
  },
  {
    id: "prism",
    name: "Captik · Devin Jatho",
    cleanName: "Devin Jatho",
    category: "Popular",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/prism.mp4",
    poster: "/previews/p/prism.webp",
    patch: {
      fontFamily: font("Space Grotesk"),
      fontWeight: 800,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 95,
      strokeOn: true,
      strokeColor: "#00F0FF",
      strokeWidth: 2.5,
      shadowOn: true,
      shadowColor: "#EC4899",
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 0,
      shadowBlur: 12,
      activeWordOn: true,
      activeWordColor: "#EC4899",
      activeWordScale: 1.18,
    }
  },
  {
    id: "highlighted_word",
    name: "Captik · Highlighted Word",
    cleanName: "Highlighted Word",
    category: "Clean",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/highlighted_word.mp4",
    poster: "/previews/p/highlighted_word.webp",
    patch: {
      fontFamily: font("Inter"),
      fontWeight: 800,
      fontSize: 44,
      textCase: "upper",
      color: "#94A3B8",
      posY: 80,
      wordsPerChunk: 3,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2.5,
      activeWordOn: true,
      activeWordColor: "#22C55E",
      activeWordScale: 1.16,
    }
  },
  {
    id: "clean_glow",
    name: "Captik · Clean Glow Style",
    cleanName: "Clean Glow Style",
    category: "Clean",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/clean_glow.mp4",
    poster: "/previews/p/clean_glow.webp",
    patch: {
      fontFamily: font("Outfit"),
      fontWeight: 700,
      fontSize: 42,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 80,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 100,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2,
      glowOn: true,
      glowColor: "#00F0FF",
      glowBlur: 16,
      glowIntensity: 80,
      activeWordOn: true,
      activeWordColor: "#67E8F9",
      activeWordScale: 1.12,
    }
  },
  {
    id: "captik_clean",
    name: "Captik · Captik Clean",
    cleanName: "Captik Clean",
    category: "Clean",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/captik_clean.mp4",
    poster: "/previews/p/captik_clean.webp",
    patch: {
      fontFamily: font("DM Sans"),
      fontWeight: 700,
      fontSize: 40,
      textCase: "normal",
      color: "#FFFFFF",
      posY: 82,
      wordsPerChunk: 3,
      transition: "pop",
      transitionSpeed: 110,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 70,
      shadowX: 0,
      shadowY: 3,
      shadowBlur: 6,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.1,
    }
  },
  {
    id: "black_punch",
    name: "Captik · Black Punch",
    cleanName: "Black Punch",
    category: "Bold & animated",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/black_punch.mp4",
    poster: "/previews/p/black_punch.webp",
    patch: {
      fontFamily: font("Archivo Black"),
      fontWeight: 900,
      fontSize: 48,
      textCase: "upper",
      color: "#000000",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#FFFFFF",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 10,
      activeWordOn: true,
      activeWordColor: "#FFE600",
      activeWordScale: 1.2,
    }
  },
  {
    id: "captik_word",
    name: "Captik · Captik Word",
    cleanName: "Captik Word",
    category: "Popular",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/captik_word.mp4",
    poster: "/previews/p/captik_word.webp",
    patch: {
      fontFamily: font("Poppins"),
      fontWeight: 900,
      fontSize: 52,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 80,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 5,
      shadowBlur: 12,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.24,
    }
  },
  {
    id: "pixelated",
    name: "Captik · Pixelated Word",
    cleanName: "Pixelated Word",
    category: "Bold & animated",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/pixelated.mp4",
    poster: "/previews/p/pixelated.webp",
    patch: {
      fontFamily: font("Press Start 2P"),
      fontWeight: 400,
      fontSize: 32,
      textCase: "upper",
      color: "#10B981",
      posY: 80,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 120,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 3,
      shadowY: 3,
      shadowBlur: 0,
      glowOn: true,
      glowColor: "#10B981",
      glowBlur: 14,
      glowIntensity: 85,
      activeWordOn: true,
      activeWordColor: "#34D399",
      activeWordScale: 1.15,
    }
  },
  {
    id: "liquid_glass",
    name: "Captik · Liquid Glass",
    cleanName: "Liquid Glass",
    category: "Clean",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/liquid_glass.mp4",
    poster: "/previews/p/liquid_glass.webp",
    patch: {
      fontFamily: font("Inter"),
      fontWeight: 600,
      fontSize: 38,
      textCase: "normal",
      color: "#F8FAFC",
      posY: 82,
      wordsPerChunk: 3,
      transition: "fade",
      transitionSpeed: 140,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 50,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 12,
      bgOn: true,
      bgColor: "rgba(255, 255, 255, 0.16)",
      bgOpacity: 85,
      bgRadius: 12,
      bgPadX: 16,
      bgPadY: 8,
      activeWordOn: true,
      activeWordColor: "#38BDF8",
      activeWordScale: 1.08,
    }
  },
  {
    id: "tabahi",
    name: "Captik · Tabahi",
    cleanName: "Tabahi",
    category: "Bold & animated",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/tabahi.mp4",
    poster: "/previews/p/tabahi.webp",
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 52,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 76,
      wordsPerChunk: 2,
      transition: "bounce",
      transitionSpeed: 85,
      strokeOn: true,
      strokeColor: "#DC2626",
      strokeWidth: 4,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 95,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 14,
      activeWordOn: true,
      activeWordColor: "#EF4444",
      activeWordScale: 1.26,
    }
  },
  {
    id: "deep_glow",
    name: "Captik · Deep Glow",
    cleanName: "Deep Glow",
    category: "Bold & animated",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/deep_glow.mp4",
    poster: "/previews/p/deep_glow.webp",
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 800,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 100,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2.5,
      glowOn: true,
      glowColor: "#8B5CF6",
      glowBlur: 24,
      glowIntensity: 90,
      activeWordOn: true,
      activeWordColor: "#C084FC",
      activeWordScale: 1.18,
    }
  },
  {
    id: "seedha_saadha",
    name: "Captik · Seedha Saadha",
    cleanName: "Seedha Saadha",
    category: "Clean",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/seedha_saadha.mp4",
    poster: "/previews/p/seedha_saadha.webp",
    patch: {
      fontFamily: font("Inter"),
      fontWeight: 600,
      fontSize: 38,
      textCase: "normal",
      color: "#F8FAFC",
      posY: 82,
      wordsPerChunk: 3,
      transition: "fade",
      transitionSpeed: 160,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 55,
      shadowX: 0,
      shadowY: 2,
      shadowBlur: 6,
      activeWordOn: true,
      activeWordColor: "#FFFFFF",
      activeWordScale: 1.05,
    }
  },
  {
    id: "thora_cinematic",
    name: "Captik · Thora Cinematic",
    cleanName: "Thora Cinematic",
    category: "Clean",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/thora_cinematic.mp4",
    poster: "/previews/p/thora_cinematic.webp",
    patch: {
      fontFamily: font("Playfair Display"),
      fontWeight: 700,
      fontSize: 40,
      textCase: "title",
      color: "#FFFFFF",
      posY: 84,
      wordsPerChunk: 3,
      transition: "fade",
      transitionSpeed: 200,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 75,
      shadowX: 0,
      shadowY: 3,
      shadowBlur: 8,
      activeWordOn: true,
      activeWordColor: "#FDE047",
      activeWordScale: 1.08,
    }
  },
  {
    id: "delhi",
    name: "Captik · Delhi",
    cleanName: "Delhi",
    category: "Bold & animated",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/delhi.mp4",
    poster: "/previews/p/delhi.webp",
    patch: {
      fontFamily: font("Plus Jakarta Sans"),
      fontWeight: 800,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 85,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 10,
      activeWordOn: true,
      activeWordColor: "#FF9933",
      activeWordScale: 1.2,
    }
  },
  {
    id: "illusion",
    name: "Captik · Illusion",
    cleanName: "Illusion",
    category: "Bold & animated",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/illusion.mp4",
    poster: "/previews/p/illusion.webp",
    patch: {
      fontFamily: font("Space Grotesk"),
      fontWeight: 800,
      fontSize: 48,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 95,
      strokeOn: true,
      strokeColor: "#FF0055",
      strokeWidth: 2,
      shadowOn: true,
      shadowColor: "#00F0FF",
      shadowOpacity: 90,
      shadowX: 3,
      shadowY: 0,
      shadowBlur: 8,
      activeWordOn: true,
      activeWordColor: "#00F0FF",
      activeWordScale: 1.2,
    }
  },
  {
    id: "editor_masala",
    name: "Captik · Editor Masala",
    cleanName: "Editor Masala",
    category: "Bold & animated",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/editor_masala.mp4",
    poster: "/previews/p/editor_masala.webp",
    patch: {
      fontFamily: font("Poppins"),
      fontWeight: 900,
      fontSize: 50,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 76,
      wordsPerChunk: 2,
      transition: "bounce",
      transitionSpeed: 85,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 4,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 95,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 12,
      activeWordOn: true,
      activeWordColor: "#F97316",
      activeWordScale: 1.25,
    }
  },
  {
    id: "aura",
    name: "Captik · Aura",
    cleanName: "Aura",
    category: "Clean",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/aura.mp4",
    poster: "/previews/p/aura.webp",
    patch: {
      fontFamily: font("Outfit"),
      fontWeight: 700,
      fontSize: 44,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 80,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 100,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2,
      glowOn: true,
      glowColor: "#FBBF24",
      glowBlur: 18,
      glowIntensity: 80,
      activeWordOn: true,
      activeWordColor: "#FCD34D",
      activeWordScale: 1.15,
    }
  },
  {
    id: "aura_helvetica",
    name: "Captik · Swiss",
    cleanName: "Swiss",
    category: "Clean",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/aura_helvetica.mp4",
    poster: "/previews/p/aura_helvetica.webp",
    patch: {
      fontFamily: font("Inter"),
      fontWeight: 700,
      fontSize: 42,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 80,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 95,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2,
      activeWordOn: true,
      activeWordColor: "#EF4444",
      activeWordScale: 1.12,
    }
  },
  {
    id: "big_reveal",
    name: "Captik · Big Reveal",
    cleanName: "Big Reveal",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/big_reveal.mp4",
    poster: "/previews/p/big_reveal.webp",
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 56,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 10,
      shadowBlur: 24,
      activeWordOn: true,
      activeWordColor: "#FFE600",
      activeWordScale: 1.25,
    }
  },
  {
    id: "big_red",
    name: "Captik · The Big Red",
    cleanName: "The Big Red",
    category: "Bold & animated",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/big_red.mp4",
    poster: "/previews/p/big_red.webp",
    patch: {
      fontFamily: font("Bebas Neue"),
      fontWeight: 900,
      fontSize: 58,
      textCase: "upper",
      color: "#EF4444",
      posY: 76,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 85,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 4.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 95,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 14,
      activeWordOn: true,
      activeWordColor: "#FFFFFF",
      activeWordScale: 1.22,
    }
  },
  {
    id: "scribble",
    name: "Captik · Scribble",
    cleanName: "Scribble",
    category: "Bold & animated",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/scribble.mp4",
    poster: "/previews/p/scribble.webp",
    patch: {
      fontFamily: font("Permanent Marker"),
      fontWeight: 700,
      fontSize: 46,
      textCase: "normal",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "bounce",
      transitionSpeed: 110,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 85,
      shadowX: 2,
      shadowY: 4,
      shadowBlur: 8,
      activeWordOn: true,
      activeWordColor: "#FDE047",
      activeWordScale: 1.2,
    }
  },
  {
    id: "archives",
    name: "Captik · Archives",
    cleanName: "Archives",
    category: "Clean",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/archives.mp4",
    poster: "/previews/p/archives.webp",
    patch: {
      fontFamily: font("Special Elite"),
      fontWeight: 700,
      fontSize: 38,
      textCase: "normal",
      color: "#FEF3C7",
      posY: 82,
      wordsPerChunk: 3,
      transition: "typewriter",
      transitionSpeed: 180,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 2,
      shadowBlur: 6,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.05,
    }
  },
  {
    id: "blockbuster",
    name: "Captik · Blockbuster",
    cleanName: "Blockbuster",
    category: "Bold & animated",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/blockbuster.mp4",
    poster: "/previews/p/blockbuster.webp",
    patch: {
      fontFamily: font("Archivo Black"),
      fontWeight: 900,
      fontSize: 52,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 76,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 85,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 4.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 16,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.24,
    }
  },
  {
    id: "journal",
    name: "Captik · Journal",
    cleanName: "Journal",
    category: "Clean",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/journal.mp4",
    poster: "/previews/p/journal.webp",
    patch: {
      fontFamily: font("DM Serif Display"),
      fontWeight: 600,
      fontSize: 40,
      textCase: "title",
      color: "#FFFBEB",
      posY: 82,
      wordsPerChunk: 3,
      transition: "fade",
      transitionSpeed: 160,
      bgOn: true,
      bgColor: "rgba(24, 24, 27, 0.85)",
      bgOpacity: 85,
      bgRadius: 8,
      bgPadX: 14,
      bgPadY: 6,
      activeWordOn: true,
      activeWordColor: "#FCD34D",
      activeWordScale: 1.08,
    }
  },
  {
    id: "interlock",
    name: "Captik · Interlock",
    cleanName: "Interlock",
    category: "Bold & animated",
    isBehindYou: false,
    isNew: false,
    video: "/previews/t/interlock.mp4",
    poster: "/previews/p/interlock.webp",
    patch: {
      fontFamily: font("Space Grotesk"),
      fontWeight: 800,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 85,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      activeWordOn: true,
      activeWordColor: "#06B6D4",
      activeWordScale: 1.18,
    }
  },
  {
    id: "look_anchorage",
    name: "Captik · Anchorage",
    cleanName: "Anchorage",
    category: "Clean",
    isBehindYou: false,
    isNew: true,
    video: "/previews/t/look_anchorage.mp4",
    poster: "/previews/p/look_anchorage.webp",
    patch: {
      fontFamily: font("Work Sans"),
      fontWeight: 800,
      fontSize: 42,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 80,
      wordsPerChunk: 2,
      transition: "slide-up",
      transitionSpeed: 120,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2,
      activeWordOn: true,
      activeWordColor: "#A5F3FC",
      activeWordScale: 1.14,
    }
  },
  {
    id: "look_beacon",
    name: "Captik · Beacon",
    cleanName: "Beacon",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_beacon.mp4",
    poster: "/previews/p/look_beacon.webp",
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#EC4899",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_cove",
    name: "Captik · Cove",
    cleanName: "Cove",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_cove.mp4",
    poster: "/previews/p/look_cove.webp",
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#F97316",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_driftwood",
    name: "Captik · Driftwood",
    cleanName: "Driftwood",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_driftwood.mp4",
    poster: "/previews/p/look_driftwood.webp",
    patch: {
      fontFamily: font("Oswald"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#A855F7",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_ellis",
    name: "Captik · Ellis",
    cleanName: "Ellis",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_ellis.mp4",
    poster: "/previews/p/look_ellis.webp",
    patch: {
      fontFamily: font("Bebas Neue"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#E11D48",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_ferrier",
    name: "Captik · Ferrier",
    cleanName: "Ferrier",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_ferrier.mp4",
    poster: "/previews/p/look_ferrier.webp",
    patch: {
      fontFamily: font("Archivo Black"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#FFE600",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_garnet",
    name: "Captik · Garnet",
    cleanName: "Garnet",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_garnet.mp4",
    poster: "/previews/p/look_garnet.webp",
    patch: {
      fontFamily: font("Black Ops One"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_hawser",
    name: "Captik · Hawser",
    cleanName: "Hawser",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_hawser.mp4",
    poster: "/previews/p/look_hawser.webp",
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#38BDF8",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_ibis",
    name: "Captik · Ibis",
    cleanName: "Ibis",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_ibis.mp4",
    poster: "/previews/p/look_ibis.webp",
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#22C55E",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_jetty",
    name: "Captik · Jetty",
    cleanName: "Jetty",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_jetty.mp4",
    poster: "/previews/p/look_jetty.webp",
    patch: {
      fontFamily: font("Oswald"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#EC4899",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_keel",
    name: "Captik · Keel",
    cleanName: "Keel",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_keel.mp4",
    poster: "/previews/p/look_keel.webp",
    patch: {
      fontFamily: font("Bebas Neue"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#F97316",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_lanyard",
    name: "Captik · Lanyard",
    cleanName: "Lanyard",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_lanyard.mp4",
    poster: "/previews/p/look_lanyard.webp",
    patch: {
      fontFamily: font("Archivo Black"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#A855F7",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_mizzen",
    name: "Captik · Mizzen",
    cleanName: "Mizzen",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_mizzen.mp4",
    poster: "/previews/p/look_mizzen.webp",
    patch: {
      fontFamily: font("Black Ops One"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#E11D48",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_netting",
    name: "Captik · Netting",
    cleanName: "Netting",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_netting.mp4",
    poster: "/previews/p/look_netting.webp",
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#FFE600",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_outhaul",
    name: "Captik · Outhaul",
    cleanName: "Outhaul",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_outhaul.mp4",
    poster: "/previews/p/look_outhaul.webp",
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_painter",
    name: "Captik · Painter",
    cleanName: "Painter",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_painter.mp4",
    poster: "/previews/p/look_painter.webp",
    patch: {
      fontFamily: font("Oswald"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#38BDF8",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_quay",
    name: "Captik · Quay",
    cleanName: "Quay",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_quay.mp4",
    poster: "/previews/p/look_quay.webp",
    patch: {
      fontFamily: font("Bebas Neue"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#22C55E",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_rudder",
    name: "Captik · Rudder",
    cleanName: "Rudder",
    category: "Popular",
    isBehindYou: false,
    isNew: true,
    video: "/previews/t/look_rudder.mp4",
    poster: "/previews/p/look_rudder.webp",
    patch: {
      fontFamily: font("Space Grotesk"),
      fontWeight: 800,
      fontSize: 44,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 85,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 10,
      posY: 80,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 95,
      activeWordOn: true,
      activeWordColor: "#00F0FF",
      activeWordScale: 1.18,
    }
  },
  {
    id: "look_scupper",
    name: "Captik · Scupper",
    cleanName: "Scupper",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_scupper.mp4",
    poster: "/previews/p/look_scupper.webp",
    patch: {
      fontFamily: font("Black Ops One"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#F97316",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_taffrail",
    name: "Captik · Taffrail",
    cleanName: "Taffrail",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_taffrail.mp4",
    poster: "/previews/p/look_taffrail.webp",
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#A855F7",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_underway",
    name: "Captik · Underway",
    cleanName: "Underway",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_underway.mp4",
    poster: "/previews/p/look_underway.webp",
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#E11D48",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_vang",
    name: "Captik · Vang",
    cleanName: "Vang",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_vang.mp4",
    poster: "/previews/p/look_vang.webp",
    patch: {
      fontFamily: font("Oswald"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#FFE600",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_windlass",
    name: "Captik · Windlass",
    cleanName: "Windlass",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_windlass.mp4",
    poster: "/previews/p/look_windlass.webp",
    patch: {
      fontFamily: font("Bebas Neue"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_yawl",
    name: "Captik · Yawl",
    cleanName: "Yawl",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_yawl.mp4",
    poster: "/previews/p/look_yawl.webp",
    patch: {
      fontFamily: font("Archivo Black"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#38BDF8",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_abbey",
    name: "Captik · Abbey",
    cleanName: "Abbey",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_abbey.mp4",
    poster: "/previews/p/look_abbey.webp",
    patch: {
      fontFamily: font("Black Ops One"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#22C55E",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_belfry",
    name: "Captik · Belfry",
    cleanName: "Belfry",
    category: "Property reels",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_belfry.mp4",
    poster: "/previews/p/look_belfry.webp",
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#EC4899",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_cloister",
    name: "Captik · Cloister",
    cleanName: "Cloister",
    category: "Property reels",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_cloister.mp4",
    poster: "/previews/p/look_cloister.webp",
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#F97316",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_dovecote",
    name: "Captik · Dovecote",
    cleanName: "Dovecote",
    category: "Property reels",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_dovecote.mp4",
    poster: "/previews/p/look_dovecote.webp",
    patch: {
      fontFamily: font("Oswald"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#A855F7",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_effigy",
    name: "Captik · Effigy",
    cleanName: "Effigy",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_effigy.mp4",
    poster: "/previews/p/look_effigy.webp",
    patch: {
      fontFamily: font("Bebas Neue"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#E11D48",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_font",
    name: "Captik · Font",
    cleanName: "Font",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_font.mp4",
    poster: "/previews/p/look_font.webp",
    patch: {
      fontFamily: font("Archivo Black"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#FFE600",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_gable",
    name: "Captik · Gable",
    cleanName: "Gable",
    category: "Property reels",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_gable.mp4",
    poster: "/previews/p/look_gable.webp",
    patch: {
      fontFamily: font("Black Ops One"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_hassock",
    name: "Captik · Hassock",
    cleanName: "Hassock",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_hassock.mp4",
    poster: "/previews/p/look_hassock.webp",
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#38BDF8",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_iron",
    name: "Captik · Iron",
    cleanName: "Iron",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_iron.mp4",
    poster: "/previews/p/look_iron.webp",
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#22C55E",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_jamb",
    name: "Captik · Jamb",
    cleanName: "Jamb",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_jamb.mp4",
    poster: "/previews/p/look_jamb.webp",
    patch: {
      fontFamily: font("Oswald"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#EC4899",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_keystone",
    name: "Captik · Keystone",
    cleanName: "Keystone",
    category: "Popular",
    isBehindYou: false,
    isNew: true,
    video: "/previews/t/look_keystone.mp4",
    poster: "/previews/p/look_keystone.webp",
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 800,
      fontSize: 44,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 85,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 10,
      posY: 80,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 95,
      activeWordOn: true,
      activeWordColor: "#38BDF8",
      activeWordScale: 1.18,
    }
  },
  {
    id: "look_lintel",
    name: "Captik · Lintel",
    cleanName: "Lintel",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_lintel.mp4",
    poster: "/previews/p/look_lintel.webp",
    patch: {
      fontFamily: font("Archivo Black"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#A855F7",
      activeWordScale: 1.25,
    }
  },
  {
    id: "look_mullion",
    name: "Captik · Mullion",
    cleanName: "Mullion",
    category: "Behind you",
    isBehindYou: true,
    isNew: false,
    video: "/previews/t/look_mullion.mp4",
    poster: "/previews/p/look_mullion.webp",
    patch: {
      fontFamily: font("Black Ops One"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      strokeOn: true,
      strokeColor: "#111111",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 18,
      posY: 42,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: "#E11D48",
      activeWordScale: 1.25,
    }
  }
];
