// All 43 Caption Templates extracted from Kalakar (https://app.kalakar.io)
// Pixel-accurate recreation with typography, animations, word highlights, strokes, and glows.
import type { CapStyle } from "./captionStyle";

const FONT_MAP: Record<string, string> = {
  "Inter": "'Inter', system-ui, sans-serif",
  "Poppins": "'Poppins', 'Inter', sans-serif",
  "Montserrat": "'Montserrat', 'Inter', sans-serif",
  "Space Grotesk": "'Space Grotesk', 'Inter', sans-serif",
  "DM Sans": "'DM Sans', 'Inter', sans-serif",
  "Outfit": "'Outfit', 'Inter', sans-serif",
  "Anton": "'Anton', 'Impact', sans-serif",
  "Archivo Black": "'Archivo Black', 'Impact', sans-serif",
  "Bebas Neue": "'Bebas Neue', 'Impact', sans-serif",
  "Bangers": "'Bangers', 'Impact', cursive",
  "Permanent Marker": "'Permanent Marker', cursive",
  "Press Start 2P": "'Press Start 2P', ui-monospace, monospace",
  "EB Garamond": "'EB Garamond', Georgia, serif",
  "Playfair Display": "'Playfair Display', Georgia, serif",
  "DM Serif Display": "'DM Serif Display', Georgia, serif",
  "Special Elite": "'Special Elite', ui-monospace, monospace",
  "Work Sans": "'Work Sans', 'Inter', sans-serif",
  "Oswald": "'Oswald', 'Impact', sans-serif",
  "Black Ops One": "'Black Ops One', 'Impact', sans-serif",
  "Plus Jakarta Sans": "'Plus Jakarta Sans', 'Inter', sans-serif",
};

const font = (label: string): string => FONT_MAP[label] ?? `'${label}', system-ui, sans-serif`;

export interface KalakarPresetItem {
  id: string;
  name: string;
  cleanName: string;
  category: "Kalakar";
  feature?: string;
  isBehindYou?: boolean;
  isNew?: boolean;
  patch: Partial<CapStyle>;
}

export const KALAKAR_43_PRESETS: KalakarPresetItem[] = [
  {
    id: "builtin-lala",
    name: "Kalakar · Lala",
    cleanName: "Lala",
    category: "Kalakar",
    feature: "Multi-color word highlight, casual script style",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Outfit"),
      fontWeight: 800,
      fontSize: 46,
      textCase: "normal",
      color: "#FFFFFF",
      posY: 80,
      wordsPerChunk: 3,
      transition: "pop",
      transitionSpeed: 100,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      activeWordOn: true,
      activeWordColor: "#F97316",
      activeWordScale: 1.18,
    }
  },
  {
    id: "builtin-ali-abdaal",
    name: "Kalakar · Ali Abdaal",
    cleanName: "Ali Abdaal",
    category: "Kalakar",
    feature: "Clean sans-serif, subtle active word accent",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Inter"),
      fontWeight: 600,
      fontSize: 38,
      textCase: "normal",
      color: "#F8FAFC",
      posY: 82,
      wordsPerChunk: 3,
      transition: "fade",
      transitionSpeed: 150,
      bgOn: true,
      bgColor: "rgba(0, 0, 0, 0.75)",
      bgOpacity: 80,
      bgRadius: 8,
      bgPadX: 14,
      bgPadY: 6,
      activeWordOn: true,
      activeWordColor: "#38BDF8",
      activeWordScale: 1.05,
    }
  },
  {
    id: "builtin-double-trouble",
    name: "Kalakar · Double Trouble",
    cleanName: "Double Trouble",
    category: "Kalakar",
    feature: "Dual word highlight box animation",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 900,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 95,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3,
      activeWordOn: true,
      activeWordColor: "#000000",
      activeWordScale: 1.15,
      activeWordBgOn: true,
      activeWordBgColor: "#FFE600",
    }
  },
  {
    id: "builtin-delhi",
    name: "Kalakar · Delhi",
    cleanName: "Delhi",
    category: "Kalakar",
    feature: "Bold uppercase, vibrant yellow & neon accent",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Plus Jakarta Sans"),
      fontWeight: 800,
      fontSize: 48,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 5,
      shadowBlur: 10,
      activeWordOn: true,
      activeWordColor: "#FF9933",
      activeWordScale: 1.2,
    }
  },
  {
    id: "builtin-kalakar-motion",
    name: "Kalakar · Kalakar Motion",
    cleanName: "Kalakar Motion",
    category: "Kalakar",
    feature: "Dynamic motion pop-in effect",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 900,
      fontSize: 48,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 76,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 80,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 12,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.24,
    }
  },
  {
    id: "builtin-kathmandu",
    name: "Kalakar · Kathmandu",
    cleanName: "Kathmandu",
    category: "Kalakar",
    feature: "Lowercase minimal, Bold, Shadow",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Inter"),
      fontWeight: 800,
      fontSize: 40,
      textCase: "lower",
      color: "#F8FAFC",
      posY: 82,
      wordsPerChunk: 3,
      transition: "fade",
      transitionSpeed: 120,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 75,
      shadowX: 0,
      shadowY: 3,
      shadowBlur: 8,
      activeWordOn: true,
      activeWordColor: "#2DD4BF",
      activeWordScale: 1.12,
    }
  },
  {
    id: "builtin-bubble-style",
    name: "Kalakar · Bubbles",
    cleanName: "Bubbles",
    category: "Kalakar",
    feature: "Rounded pill background pop",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Bangers"),
      fontWeight: 800,
      fontSize: 52,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "bounce",
      transitionSpeed: 110,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 95,
      shadowX: 3,
      shadowY: 3,
      shadowBlur: 0,
      activeWordOn: true,
      activeWordColor: "#FFE600",
      activeWordScale: 1.25,
    }
  },
  {
    id: "builtin-ij-template",
    name: "Kalakar · IJ Template",
    cleanName: "IJ Template",
    category: "Kalakar",
    feature: "Irfan Junejo signature style with custom primary color & blur adjustment",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Inter"),
      fontWeight: 700,
      fontSize: 42,
      textCase: "upper",
      color: "#FFFBEB",
      posY: 80,
      wordsPerChunk: 3,
      transition: "fade",
      transitionSpeed: 160,
      strokeOn: true,
      strokeColor: "rgba(0,0,0,0.85)",
      strokeWidth: 2,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 12,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.15,
    }
  },
  {
    id: "builtin-kalakar-glow",
    name: "Kalakar · Kalakar Glow",
    cleanName: "Kalakar Glow",
    category: "Kalakar",
    feature: "Neon text glow, Bold, Shadow",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Space Grotesk"),
      fontWeight: 800,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 95,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2.5,
      glowOn: true,
      glowColor: "#00F0FF",
      glowBlur: 20,
      glowIntensity: 90,
      activeWordOn: true,
      activeWordColor: "#67E8F9",
      activeWordScale: 1.18,
    }
  },
  {
    id: "builtin-clean-motion",
    name: "Kalakar · Clean Motion",
    cleanName: "Clean Motion",
    category: "Kalakar",
    feature: "Smooth word-by-word motion (Free Render)",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Inter"),
      fontWeight: 700,
      fontSize: 40,
      textCase: "normal",
      color: "#FFFFFF",
      posY: 82,
      wordsPerChunk: 3,
      transition: "slide-up",
      transitionSpeed: 140,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 60,
      shadowX: 0,
      shadowY: 2,
      shadowBlur: 6,
      activeWordOn: true,
      activeWordColor: "#E0E7FF",
      activeWordScale: 1.08,
    }
  },
  {
    id: "builtin-goa",
    name: "Kalakar · Goa",
    cleanName: "Goa",
    category: "Kalakar",
    feature: "Tropical contrast colors, Bold, Shadow",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 800,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 95,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 85,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 10,
      activeWordOn: true,
      activeWordColor: "#F43F5E",
      activeWordScale: 1.2,
    }
  },
  {
    id: "builtin-islamabad",
    name: "Kalakar · Islamabad",
    cleanName: "Islamabad",
    category: "Kalakar",
    feature: "Italic serif accent, Shadow",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Playfair Display"),
      fontWeight: 700,
      fontSize: 42,
      textCase: "title",
      color: "#FFFFFF",
      posY: 82,
      wordsPerChunk: 3,
      transition: "fade",
      transitionSpeed: 180,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 3,
      shadowBlur: 8,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.1,
    }
  },
  {
    id: "builtin-mumbai",
    name: "Kalakar · Mumbai",
    cleanName: "Mumbai",
    category: "Kalakar",
    feature: "High-contrast yellow/cyan accent, Bold, Shadow",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Bebas Neue"),
      fontWeight: 900,
      fontSize: 52,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 5,
      shadowBlur: 10,
      activeWordOn: true,
      activeWordColor: "#FACC15",
      activeWordScale: 1.22,
    }
  },
  {
    id: "builtin-karachi",
    name: "Kalakar · Karachi",
    cleanName: "Karachi",
    category: "Kalakar",
    feature: "Stacked vertical line pop, Shadow",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 50,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 76,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 85,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 4,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 95,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 12,
      activeWordOn: true,
      activeWordColor: "#EF4444",
      activeWordScale: 1.25,
    }
  },
  {
    id: "builtin-shamani",
    name: "Kalakar · Shamani",
    cleanName: "Shamani",
    category: "Kalakar",
    feature: "Raj Shamani signature style, spaced uppercase",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 800,
      fontSize: 44,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 80,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 10,
      activeWordOn: true,
      activeWordColor: "#FFE600",
      activeWordScale: 1.2,
    }
  },
  {
    id: "builtin-shamani-2",
    name: "Kalakar · Shamani 2",
    cleanName: "Shamani 2",
    category: "Kalakar",
    feature: "Raj Shamani double-stacked repetition style",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 52,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 76,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 85,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 4,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 14,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.25,
    }
  },
  {
    id: "builtin-flicker",
    name: "Kalakar · Flicker",
    cleanName: "Flicker",
    category: "Kalakar",
    feature: "Rapid text flicker animation effect",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Space Grotesk"),
      fontWeight: 800,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 80,
      wordsPerChunk: 2,
      transition: "typewriter",
      transitionSpeed: 75,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2,
      glowOn: true,
      glowColor: "#00F0FF",
      glowBlur: 14,
      glowIntensity: 85,
      activeWordOn: true,
      activeWordColor: "#00F0FF",
      activeWordScale: 1.15,
    }
  },
  {
    id: "builtin-underline",
    name: "Kalakar · Underline",
    cleanName: "Underline",
    category: "Kalakar",
    feature: "Animated underline accent on spoken word",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Inter"),
      fontWeight: 700,
      fontSize: 42,
      textCase: "normal",
      color: "#FFFFFF",
      posY: 82,
      wordsPerChunk: 3,
      transition: "fade",
      transitionSpeed: 120,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 70,
      shadowX: 0,
      shadowY: 3,
      shadowBlur: 6,
      activeWordOn: true,
      activeWordColor: "#38BDF8",
      activeWordScale: 1.1,
    }
  },
  {
    id: "builtin-green-pop",
    name: "Kalakar · Pop Up",
    cleanName: "Pop Up",
    category: "Kalakar",
    feature: "Scale pop-up animation, Bold, Shadow",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 50,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 85,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 4,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 12,
      activeWordOn: true,
      activeWordColor: "#10B981",
      activeWordScale: 1.25,
    }
  },
  {
    id: "builtin-dhaka",
    name: "Kalakar · Dhaka",
    cleanName: "Dhaka",
    category: "Kalakar",
    feature: "Classic subtitle layout, Bold, Shadow",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Poppins"),
      fontWeight: 700,
      fontSize: 42,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 80,
      wordsPerChunk: 3,
      transition: "pop",
      transitionSpeed: 100,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 85,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      activeWordOn: true,
      activeWordColor: "#EAB308",
      activeWordScale: 1.16,
    }
  },
  {
    id: "builtin-kalakar-shadow",
    name: "Kalakar · Kalakar Shadow",
    cleanName: "Kalakar Shadow",
    category: "Kalakar",
    feature: "Deep drop shadow, high contrast readability",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 900,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 80,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 100,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 95,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 14,
      activeWordOn: true,
      activeWordColor: "#FACC15",
      activeWordScale: 1.15,
    }
  },
  {
    id: "builtin-kalakar",
    name: "Kalakar · Kalakar",
    cleanName: "Kalakar",
    category: "Kalakar",
    feature: "Standard original Kalakar subtitle style",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Plus Jakarta Sans"),
      fontWeight: 800,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 79,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 85,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.16,
    }
  },
  {
    id: "builtin-hormozi-style",
    name: "Kalakar · Hormozi Style",
    cleanName: "Hormozi Style",
    category: "Kalakar",
    feature: "Alex Hormozi style (Impact font, yellow/green highlight, shadow)",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 50,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 4.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 95,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 12,
      activeWordOn: true,
      activeWordColor: "#FFE600",
      activeWordScale: 1.25,
    }
  },
  {
    id: "builtin-editing-skool",
    name: "Kalakar · Editing Skool",
    cleanName: "Editing Skool",
    category: "Kalakar",
    feature: "Signature Editing Skool style (Free Render)",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 900,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 95,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3,
      activeWordOn: true,
      activeWordColor: "#000000",
      activeWordScale: 1.15,
      activeWordBgOn: true,
      activeWordBgColor: "#00F0FF",
    }
  },
  {
    id: "builtin-mr-beast-style-1",
    name: "Kalakar · Mr Beast Style 1",
    cleanName: "Mr Beast Style 1",
    category: "Kalakar",
    feature: "Large impact font, yellow highlight, shadow",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 52,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 76,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 85,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 4,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 10,
      activeWordOn: true,
      activeWordColor: "#FFE600",
      activeWordScale: 1.22,
      activeWordBgOn: true,
      activeWordBgColor: "#DC2626",
    }
  },
  {
    id: "builtin-mr-beast-style-2",
    name: "Kalakar · Mr Beast Style 2",
    cleanName: "Mr Beast Style 2",
    category: "Kalakar",
    feature: "Rotated text with thick stroke & shadow",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Archivo Black"),
      fontWeight: 900,
      fontSize: 50,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 76,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 4.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 10,
      activeWordOn: true,
      activeWordColor: "#22C55E",
      activeWordScale: 1.24,
    }
  },
  {
    id: "builtin-iman-gadzhi",
    name: "Kalakar · Iman Gadzhi",
    cleanName: "Iman Gadzhi",
    category: "Kalakar",
    feature: "Luxury minimalist editorial style",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("EB Garamond"),
      fontWeight: 700,
      fontSize: 42,
      textCase: "title",
      color: "#FFFBEB",
      posY: 82,
      wordsPerChunk: 3,
      transition: "fade",
      transitionSpeed: 180,
      glowOn: true,
      glowColor: "#D4AF37",
      glowBlur: 14,
      glowIntensity: 70,
      bgOn: true,
      bgColor: "rgba(15, 15, 20, 0.75)",
      bgOpacity: 80,
      bgRadius: 6,
      bgPadX: 16,
      bgPadY: 6,
      activeWordOn: true,
      activeWordColor: "#FCD34D",
      activeWordScale: 1.08,
    }
  },
  {
    id: "builtin-devin-jatho",
    name: "Kalakar · Devin Jatho",
    cleanName: "Devin Jatho",
    category: "Kalakar",
    feature: "Creator style with sharp shadow drop",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Space Grotesk"),
      fontWeight: 800,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 95,
      strokeOn: true,
      strokeColor: "#00F0FF",
      strokeWidth: 2.5,
      shadowOn: true,
      shadowColor: "#EC4899",
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 0,
      shadowBlur: 12,
      activeWordOn: true,
      activeWordColor: "#EC4899",
      activeWordScale: 1.18,
    }
  },
  {
    id: "builtin-highlighted-word",
    name: "Kalakar · Highlighted Word",
    cleanName: "Highlighted Word",
    category: "Kalakar",
    feature: "Solid background box highlight on active word",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Inter"),
      fontWeight: 800,
      fontSize: 44,
      textCase: "upper",
      color: "#94A3B8",
      posY: 80,
      wordsPerChunk: 3,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2.5,
      activeWordOn: true,
      activeWordColor: "#22C55E",
      activeWordScale: 1.16,
    }
  },
  {
    id: "builtin-clean-glow-style",
    name: "Kalakar · Clean Glow Style",
    cleanName: "Clean Glow Style",
    category: "Kalakar",
    feature: "Soft outline glow effect, Shadow",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Outfit"),
      fontWeight: 700,
      fontSize: 42,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 80,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 100,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2,
      glowOn: true,
      glowColor: "#00F0FF",
      glowBlur: 16,
      glowIntensity: 80,
      activeWordOn: true,
      activeWordColor: "#67E8F9",
      activeWordScale: 1.12,
    }
  },
  {
    id: "builtin-kalakar-clean",
    name: "Kalakar · Kalakar Clean",
    cleanName: "Kalakar Clean",
    category: "Kalakar",
    feature: "Ultra-clean minimal subtitle overlay",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("DM Sans"),
      fontWeight: 700,
      fontSize: 40,
      textCase: "normal",
      color: "#FFFFFF",
      posY: 82,
      wordsPerChunk: 3,
      transition: "pop",
      transitionSpeed: 110,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 70,
      shadowX: 0,
      shadowY: 3,
      shadowBlur: 6,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.1,
    }
  },
  {
    id: "builtin-black-punch",
    name: "Kalakar · Black Punch",
    cleanName: "Black Punch",
    category: "Kalakar",
    feature: "Solid black punch box background",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Archivo Black"),
      fontWeight: 900,
      fontSize: 48,
      textCase: "upper",
      color: "#000000",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#FFFFFF",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 10,
      activeWordOn: true,
      activeWordColor: "#FFE600",
      activeWordScale: 1.2,
    }
  },
  {
    id: "builtin-kalakar-word",
    name: "Kalakar · Kalakar Word",
    cleanName: "Kalakar Word",
    category: "Kalakar",
    feature: "One word at a time mode (Free Render)",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Poppins"),
      fontWeight: 900,
      fontSize: 52,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 1,
      transition: "pop",
      transitionSpeed: 80,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 5,
      shadowBlur: 12,
      activeWordOn: true,
      activeWordColor: "#F59E0B",
      activeWordScale: 1.24,
    }
  },
  {
    id: "builtin-pixelated-word",
    name: "Kalakar · Pixelated Word",
    cleanName: "Pixelated Word",
    category: "Kalakar",
    feature: "Retro 8-bit arcade font effect",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Press Start 2P"),
      fontWeight: 400,
      fontSize: 32,
      textCase: "upper",
      color: "#10B981",
      posY: 80,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 120,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 3,
      shadowY: 3,
      shadowBlur: 0,
      glowOn: true,
      glowColor: "#10B981",
      glowBlur: 14,
      glowIntensity: 85,
      activeWordOn: true,
      activeWordColor: "#34D399",
      activeWordScale: 1.15,
    }
  },
  {
    id: "builtin-ziada",
    name: "Kalakar · Ziada",
    cleanName: "Ziada",
    category: "Kalakar",
    feature: "High impact bold Hindi/Urdu content style",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Archivo Black"),
      fontWeight: 900,
      fontSize: 50,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 76,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 90,
      strokeOn: true,
      strokeColor: "#EA580C",
      strokeWidth: 4,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 95,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 12,
      activeWordOn: true,
      activeWordColor: "#F97316",
      activeWordScale: 1.24,
    }
  },
  {
    id: "builtin-liquid-glass",
    name: "Kalakar · Liquid Glass",
    cleanName: "Liquid Glass",
    category: "Kalakar",
    feature: "Frosted glass text background effect",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Inter"),
      fontWeight: 600,
      fontSize: 38,
      textCase: "normal",
      color: "#F8FAFC",
      posY: 82,
      wordsPerChunk: 3,
      transition: "fade",
      transitionSpeed: 140,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 50,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 12,
      bgOn: true,
      bgColor: "rgba(255, 255, 255, 0.16)",
      bgOpacity: 85,
      bgRadius: 12,
      bgPadX: 16,
      bgPadY: 8,
      activeWordOn: true,
      activeWordColor: "#38BDF8",
      activeWordScale: 1.08,
    }
  },
  {
    id: "builtin-top-up",
    name: "Kalakar · Top Up",
    cleanName: "Top Up",
    category: "Kalakar",
    feature: "Slide-up entrance animation, Bold, Shadow",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 800,
      fontSize: 44,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "slide-up",
      transitionSpeed: 100,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 85,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 10,
      activeWordOn: true,
      activeWordColor: "#22C55E",
      activeWordScale: 1.2,
    }
  },
  {
    id: "builtin-mota",
    name: "Kalakar · Mota",
    cleanName: "Mota",
    category: "Kalakar",
    feature: "Extra thick heavy typography, Shadow",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Archivo Black"),
      fontWeight: 900,
      fontSize: 54,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 76,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 85,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 5,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 8,
      shadowBlur: 16,
      activeWordOn: true,
      activeWordColor: "#FFE600",
      activeWordScale: 1.28,
    }
  },
  {
    id: "builtin-tabahi",
    name: "Kalakar · Tabahi",
    cleanName: "Tabahi",
    category: "Kalakar",
    feature: "High-energy explosive style, Shadow",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Anton"),
      fontWeight: 900,
      fontSize: 52,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 76,
      wordsPerChunk: 2,
      transition: "bounce",
      transitionSpeed: 85,
      strokeOn: true,
      strokeColor: "#DC2626",
      strokeWidth: 4,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 95,
      shadowX: 0,
      shadowY: 6,
      shadowBlur: 14,
      activeWordOn: true,
      activeWordColor: "#EF4444",
      activeWordScale: 1.26,
    }
  },
  {
    id: "builtin-deep-glow",
    name: "Kalakar · Deep Glow",
    cleanName: "Deep Glow",
    category: "Kalakar",
    feature: "Multi-pass neon glow bloom effect",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Montserrat"),
      fontWeight: 800,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "pop",
      transitionSpeed: 100,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2.5,
      glowOn: true,
      glowColor: "#8B5CF6",
      glowBlur: 24,
      glowIntensity: 90,
      activeWordOn: true,
      activeWordColor: "#C084FC",
      activeWordScale: 1.18,
    }
  },
  {
    id: "builtin-seedha-saadha",
    name: "Kalakar · Seedha Saadha",
    cleanName: "Seedha Saadha",
    category: "Kalakar",
    feature: "Simple straight subtitle, minimal shadow",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Inter"),
      fontWeight: 600,
      fontSize: 38,
      textCase: "normal",
      color: "#F8FAFC",
      posY: 82,
      wordsPerChunk: 3,
      transition: "fade",
      transitionSpeed: 160,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 55,
      shadowX: 0,
      shadowY: 2,
      shadowBlur: 6,
      activeWordOn: true,
      activeWordColor: "#FFFFFF",
      activeWordScale: 1.05,
    }
  },
  {
    id: "builtin-thora-cinematic",
    name: "Kalakar · Thora Cinematic",
    cleanName: "Thora Cinematic",
    category: "Kalakar",
    feature: "Widescreen movie subtitle aesthetic",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Playfair Display"),
      fontWeight: 700,
      fontSize: 40,
      textCase: "title",
      color: "#FFFFFF",
      posY: 84,
      wordsPerChunk: 3,
      transition: "fade",
      transitionSpeed: 200,
      shadowOn: true,
      shadowColor: "#000000",
      shadowOpacity: 75,
      shadowX: 0,
      shadowY: 3,
      shadowBlur: 8,
      activeWordOn: true,
      activeWordColor: "#FDE047",
      activeWordScale: 1.08,
    }
  },
  {
    id: "builtin-zero-gravity",
    name: "Kalakar · Zero Gravity",
    cleanName: "Zero Gravity",
    category: "Kalakar",
    feature: "Floating animation effect",
    isBehindYou: false,
    isNew: false,
    patch: {
      fontFamily: font("Space Grotesk"),
      fontWeight: 800,
      fontSize: 46,
      textCase: "upper",
      color: "#FFFFFF",
      posY: 78,
      wordsPerChunk: 2,
      transition: "bounce",
      transitionSpeed: 120,
      strokeOn: true,
      strokeColor: "#000000",
      strokeWidth: 2,
      glowOn: true,
      glowColor: "#3B82F6",
      glowBlur: 16,
      glowIntensity: 80,
      activeWordOn: true,
      activeWordColor: "#60A5FA",
      activeWordScale: 1.2,
    }
  }
];
