// Comprehensive language catalog: all Indian scheduled languages + widely spoken world languages.
// Codes follow BCP-47 (ISO-639-1 where available, ISO-639-3 for regional Indian languages).
export type Language = {
  code: string;
  name: string;       // English name
  native?: string;    // Native / endonym
  region?: "India" | "Asia" | "Europe" | "Africa" | "Americas" | "Middle East" | "Oceania";
  rtl?: boolean;
};

export const LANGUAGES: Language[] = [
  { code: "kfa", name: "Kodava", native: "ಕೊಡವ", region: "India" },
  { code: "beo", name: "Beary", native: "బేరి", region: "India" },
  { code: "bfq", name: "Badaga", native: "ಬಡಗ", region: "India" },
  { code: "mbf", name: "Malvani", native: "मालवणी", region: "India" },
  { code: "hlb", name: "Halbi", native: "हल्बी", region: "India" },
  { code: "spv", name: "Sambalpuri", native: "ସମ୍ବଲପୁରୀ", region: "India" },
  { code: "sjp", name: "Surjapuri", native: "सुरजापुरी", region: "India" },
  { code: "swv", name: "Shekhawati", native: "शेखावाटी", region: "India" },
  { code: "wtm", name: "Mewati", native: "मेवाती", region: "India" },
  { code: "mpt", name: "Malvi", native: "मालवी", region: "India" },
  { code: "noe", name: "Nimadi", native: "निमाड़ी", region: "India" },
  { code: "bfy", name: "Bagheli", native: "बघेली", region: "India" },
  { code: "him", name: "Himachali / Pahari", native: "हिमाचली", region: "India" },
  { code: "gbm", name: "Garhwali", native: "गढ़वाली", region: "India" },
  { code: "kum", name: "Kumaoni", native: "कुमाऊँनी", region: "India" },
  { code: "anp", name: "Angika", native: "अंगिका", region: "India" },
  { code: "bnd", name: "Bundeli", native: "बुंदेली", region: "India" },
  { code: "pa-Latn", name: "Punglish", native: "Punglish", region: "India" },
  { code: "ml-Latn", name: "Manglish", native: "Manglish", region: "India" },
  { code: "kn-Latn", name: "Kanglish", native: "Kanglish", region: "India" },
  { code: "gu-Latn", name: "Gujlish", native: "Gujlish", region: "India" },
  { code: "mr-Latn", name: "Minglish", native: "Minglish", region: "India" },
  { code: "te-Latn", name: "Teluglish", native: "Teluglish", region: "India" },
  { code: "ta-Latn", name: "Tanglish", native: "Tanglish", region: "India" },
  // ── India: 22 scheduled + widely used regional ─────────────────────────
  { code: "hi",     name: "Hindi",       native: "हिन्दी",       region: "India" },
  { code: "hi-Latn", name: "Hinglish",    native: "Hinglish",     region: "India" },
  { code: "en-IN",  name: "English (India)", native: "English",  region: "India" },
  { code: "bn",     name: "Bengali",     native: "বাংলা",       region: "India" },
  { code: "ta",     name: "Tamil",       native: "தமிழ்",        region: "India" },
  { code: "te",     name: "Telugu",      native: "తెలుగు",       region: "India" },
  { code: "mr",     name: "Marathi",     native: "मराठी",         region: "India" },
  { code: "gu",     name: "Gujarati",    native: "ગુજરાતી",       region: "India" },
  { code: "kn",     name: "Kannada",     native: "ಕನ್ನಡ",         region: "India" },
  { code: "ml",     name: "Malayalam",   native: "മലയാളം",       region: "India" },
  { code: "pa",     name: "Punjabi",     native: "ਪੰਜਾਬੀ",         region: "India" },
  { code: "ur",     name: "Urdu",        native: "اُردُو",         region: "India", rtl: true },
  { code: "or",     name: "Odia",        native: "ଓଡ଼ିଆ",         region: "India" },
  { code: "as",     name: "Assamese",    native: "অসমীয়া",      region: "India" },
  { code: "ne",     name: "Nepali",      native: "नेपाली",        region: "India" },
  { code: "sa",     name: "Sanskrit",    native: "संस्कृतम्",       region: "India" },
  { code: "sd",     name: "Sindhi",      native: "سنڌي",         region: "India", rtl: true },
  { code: "ks",     name: "Kashmiri",    native: "کٲشُر",         region: "India", rtl: true },
  { code: "kok",    name: "Konkani",     native: "कोंकणी",       region: "India" },
  { code: "mai",    name: "Maithili",    native: "मैथिली",        region: "India" },
  { code: "mni",    name: "Manipuri",    native: "মৈতৈলোন্",     region: "India" },
  { code: "sat",    name: "Santali",     native: "ᱥᱟᱱᱛᱟᱲᱤ",       region: "India" },
  { code: "doi",    name: "Dogri",       native: "डोगरी",         region: "India" },
  { code: "brx",    name: "Bodo",        native: "बड़ो",           region: "India" },
  { code: "bho",    name: "Bhojpuri",    native: "भोजपुरी",       region: "India" },
  { code: "raj",    name: "Rajasthani",  native: "राजस्थानी",     region: "India" },
  { code: "awa",    name: "Awadhi",      native: "अवधी",          region: "India" },
  { code: "mag",    name: "Magahi",      native: "मगही",           region: "India" },
  { code: "hne",    name: "Chhattisgarhi", native: "छत्तीसगढ़ी", region: "India" },
  { code: "gom",    name: "Goan Konkani", native: "गोंयची कोंकणी", region: "India" },
  { code: "tcy",    name: "Tulu",        native: "ತುಳು",           region: "India" },
  { code: "kha",    name: "Khasi",       native: "Khasi",         region: "India" },
  { code: "lus",    name: "Mizo",        native: "Mizo ṭawng",    region: "India" },
  { code: "grt",    name: "Garo",        native: "A·chik",        region: "India" },
  { code: "nag",    name: "Nagamese",    native: "Nagamese",      region: "India" },
  { code: "sck",    name: "Sadri",       native: "सादरी",         region: "India" },
  { code: "gon",    name: "Gondi",       native: "गोंडी",          region: "India" },
  { code: "kru",    name: "Kurukh",      native: "कुड़ुख़",        region: "India" },
  { code: "mwr",    name: "Marwari",     native: "मारवाड़ी",       region: "India" },
  { code: "hne-CG", name: "Haryanvi",    native: "हरियाणवी",     region: "India" },
  { code: "bpy",    name: "Bishnupriya", native: "বিষ্ণুপ্রিয়া", region: "India" },
  { code: "lep",    name: "Lepcha",      native: "ᰛᰩᰵᰛᰧᰵᰶ",         region: "India" },

  // ── South Asia (Pakistan / Bangladesh / Sri Lanka / Afghanistan / Bhutan / Maldives) ─
  { code: "ur-PK",  name: "Urdu (Pakistan)", native: "اُردُو (پاکستان)", region: "Asia", rtl: true },
  { code: "pnb",    name: "Punjabi (Shahmukhi)", native: "پن٘جابی",      region: "Asia", rtl: true },
  { code: "skr",    name: "Saraiki",     native: "سرائیکی",       region: "Asia", rtl: true },
  { code: "sd-PK",  name: "Sindhi (Pakistan)", native: "سنڌي",     region: "Asia", rtl: true },
  { code: "bal",    name: "Balochi",     native: "بلۏچی",          region: "Asia", rtl: true },
  { code: "brh",    name: "Brahui",      native: "براہوئی",        region: "Asia", rtl: true },
  { code: "hno",    name: "Hindko",      native: "ہندکو",          region: "Asia", rtl: true },
  { code: "khw",    name: "Khowar",      native: "کھوار",          region: "Asia", rtl: true },
  { code: "shi",    name: "Shina",       native: "ݜݨیاٗ",           region: "Asia", rtl: true },
  { code: "bft",    name: "Balti",       native: "སྦལ་ཏི།",         region: "Asia" },
  { code: "wbl",    name: "Wakhi",       native: "وخی",           region: "Asia", rtl: true },
  { code: "prs",    name: "Dari",        native: "دری",            region: "Asia", rtl: true },
  { code: "haz",    name: "Hazaragi",    native: "هزارگی",         region: "Asia", rtl: true },
  { code: "uzb-AF", name: "Uzbek (Afghanistan)", native: "اوزبیک", region: "Asia", rtl: true },
  { code: "dz",     name: "Dzongkha",    native: "རྫོང་ཁ",          region: "Asia" },
  { code: "bo",     name: "Tibetan",     native: "བོད་སྐད་",        region: "Asia" },
  { code: "dv",     name: "Dhivehi",     native: "ދިވެހި",          region: "Asia", rtl: true },



  // ── Asia ───────────────────────────────────────────────────────────────
  { code: "en",     name: "English",           native: "English",   region: "Asia" },
  { code: "zh",     name: "Chinese (Simplified)",  native: "简体中文", region: "Asia" },
  { code: "zh-TW",  name: "Chinese (Traditional)", native: "繁體中文", region: "Asia" },
  { code: "yue",    name: "Cantonese",         native: "粵語",       region: "Asia" },
  { code: "ja",     name: "Japanese",          native: "日本語",     region: "Asia" },
  { code: "ko",     name: "Korean",            native: "한국어",     region: "Asia" },
  { code: "vi",     name: "Vietnamese",        native: "Tiếng Việt", region: "Asia" },
  { code: "th",     name: "Thai",              native: "ไทย",         region: "Asia" },
  { code: "id",     name: "Indonesian",        native: "Bahasa Indonesia", region: "Asia" },
  { code: "ms",     name: "Malay",             native: "Bahasa Melayu", region: "Asia" },
  { code: "tl",     name: "Tagalog / Filipino", native: "Filipino",  region: "Asia" },
  { code: "my",     name: "Burmese",           native: "မြန်မာ",     region: "Asia" },
  { code: "km",     name: "Khmer",             native: "ខ្មែរ",       region: "Asia" },
  { code: "lo",     name: "Lao",               native: "ລາວ",         region: "Asia" },
  { code: "si",     name: "Sinhala",           native: "සිංහල",      region: "Asia" },
  { code: "mn",     name: "Mongolian",         native: "Монгол",     region: "Asia" },
  { code: "kk",     name: "Kazakh",            native: "Қазақ",       region: "Asia" },
  { code: "uz",     name: "Uzbek",             native: "Oʻzbek",      region: "Asia" },
  { code: "ky",     name: "Kyrgyz",            native: "Кыргызча",   region: "Asia" },
  { code: "tg",     name: "Tajik",             native: "Тоҷикӣ",     region: "Asia" },
  { code: "tk",     name: "Turkmen",           native: "Türkmen",    region: "Asia" },
  { code: "ps",     name: "Pashto",            native: "پښتو",        region: "Asia", rtl: true },
  { code: "ps-PK",  name: "Pashto (Pakistan)", native: "پښتو (پاکستان)", region: "Asia", rtl: true },
  { code: "ug",     name: "Uyghur",            native: "ئۇيغۇرچە",     region: "Asia", rtl: true },
  { code: "ii",     name: "Sichuan Yi",        native: "ꆈꌠꉙ",         region: "Asia" },
  { code: "za",     name: "Zhuang",            native: "Vahcuengh",   region: "Asia" },
  { code: "jv",     name: "Javanese",          native: "Basa Jawa",   region: "Asia" },
  { code: "su",     name: "Sundanese",         native: "Basa Sunda",  region: "Asia" },
  { code: "min",    name: "Minangkabau",       native: "Baso Minang", region: "Asia" },
  { code: "ace",    name: "Acehnese",          native: "Bahsa Acèh",  region: "Asia" },
  { code: "bug",    name: "Buginese",          native: "ᨅᨔ ᨕᨘᨁᨗ",     region: "Asia" },
  { code: "ban",    name: "Balinese",          native: "Basa Bali",   region: "Asia" },
  { code: "ceb",    name: "Cebuano",           native: "Sinugbuanon", region: "Asia" },
  { code: "ilo",    name: "Ilocano",           native: "Ilokano",     region: "Asia" },
  { code: "hil",    name: "Hiligaynon",        native: "Ilonggo",     region: "Asia" },
  { code: "war",    name: "Waray",             native: "Winaray",     region: "Asia" },
  { code: "pam",    name: "Kapampangan",       native: "Kapampangan", region: "Asia" },
  { code: "bcl",    name: "Bikol",             native: "Bikol",       region: "Asia" },



  // ── Middle East / North Africa ────────────────────────────────────────
  { code: "ar",     name: "Arabic",            native: "العربية",     region: "Middle East", rtl: true },
  { code: "he",     name: "Hebrew",            native: "עברית",       region: "Middle East", rtl: true },
  { code: "fa",     name: "Persian (Farsi)",   native: "فارسی",       region: "Middle East", rtl: true },
  { code: "tr",     name: "Turkish",           native: "Türkçe",      region: "Middle East" },
  { code: "ku",     name: "Kurdish",           native: "Kurdî",       region: "Middle East" },
  { code: "az",     name: "Azerbaijani",       native: "Azərbaycan",  region: "Middle East" },
  { code: "hy",     name: "Armenian",          native: "Հայերեն",    region: "Middle East" },
  { code: "ka",     name: "Georgian",          native: "ქართული",   region: "Middle East" },
  { code: "ckb",    name: "Kurdish (Sorani)",  native: "کوردیی ناوەندی", region: "Middle East", rtl: true },
  { code: "arz",    name: "Egyptian Arabic",   native: "مصرى",       region: "Middle East", rtl: true },
  { code: "ary",    name: "Moroccan Arabic (Darija)", native: "الدارجة", region: "Middle East", rtl: true },
  { code: "arq",    name: "Algerian Arabic",   native: "دزيرية",     region: "Middle East", rtl: true },
  { code: "acm",    name: "Iraqi Arabic",      native: "عراقي",      region: "Middle East", rtl: true },
  { code: "apc",    name: "Levantine Arabic",  native: "شامي",       region: "Middle East", rtl: true },
  { code: "ayl",    name: "Libyan Arabic",     native: "ليبي",       region: "Middle East", rtl: true },
  { code: "aeb",    name: "Tunisian Arabic",   native: "تونسي",      region: "Middle East", rtl: true },
  { code: "yi",     name: "Yiddish",           native: "ייִדיש",       region: "Middle East", rtl: true },
  { code: "syr",    name: "Syriac",            native: "ܣܘܪܝܝܐ",     region: "Middle East", rtl: true },


  // ── Europe ────────────────────────────────────────────────────────────
  { code: "es",     name: "Spanish",           native: "Español",     region: "Europe" },
  { code: "es-MX",  name: "Spanish (Mexico)",  native: "Español (MX)", region: "Americas" },
  { code: "pt",     name: "Portuguese",        native: "Português",   region: "Europe" },
  { code: "pt-BR",  name: "Portuguese (Brazil)", native: "Português (BR)", region: "Americas" },
  { code: "fr",     name: "French",            native: "Français",    region: "Europe" },
  { code: "de",     name: "German",            native: "Deutsch",     region: "Europe" },
  { code: "it",     name: "Italian",           native: "Italiano",    region: "Europe" },
  { code: "nl",     name: "Dutch",             native: "Nederlands",  region: "Europe" },
  { code: "pl",     name: "Polish",            native: "Polski",      region: "Europe" },
  { code: "ru",     name: "Russian",           native: "Русский",     region: "Europe" },
  { code: "uk",     name: "Ukrainian",         native: "Українська",  region: "Europe" },
  { code: "be",     name: "Belarusian",        native: "Беларуская",  region: "Europe" },
  { code: "cs",     name: "Czech",             native: "Čeština",     region: "Europe" },
  { code: "sk",     name: "Slovak",            native: "Slovenčina",  region: "Europe" },
  { code: "hu",     name: "Hungarian",         native: "Magyar",      region: "Europe" },
  { code: "ro",     name: "Romanian",          native: "Română",      region: "Europe" },
  { code: "bg",     name: "Bulgarian",         native: "Български",   region: "Europe" },
  { code: "sr",     name: "Serbian",           native: "Српски",      region: "Europe" },
  { code: "hr",     name: "Croatian",          native: "Hrvatski",    region: "Europe" },
  { code: "bs",     name: "Bosnian",           native: "Bosanski",    region: "Europe" },
  { code: "sl",     name: "Slovenian",         native: "Slovenščina", region: "Europe" },
  { code: "mk",     name: "Macedonian",        native: "Македонски",  region: "Europe" },
  { code: "sq",     name: "Albanian",          native: "Shqip",       region: "Europe" },
  { code: "el",     name: "Greek",             native: "Ελληνικά",    region: "Europe" },
  { code: "sv",     name: "Swedish",           native: "Svenska",     region: "Europe" },
  { code: "no",     name: "Norwegian",         native: "Norsk",       region: "Europe" },
  { code: "da",     name: "Danish",            native: "Dansk",       region: "Europe" },
  { code: "fi",     name: "Finnish",           native: "Suomi",       region: "Europe" },
  { code: "is",     name: "Icelandic",         native: "Íslenska",    region: "Europe" },
  { code: "et",     name: "Estonian",          native: "Eesti",       region: "Europe" },
  { code: "lv",     name: "Latvian",           native: "Latviešu",    region: "Europe" },
  { code: "lt",     name: "Lithuanian",        native: "Lietuvių",    region: "Europe" },
  { code: "ga",     name: "Irish",             native: "Gaeilge",     region: "Europe" },
  { code: "cy",     name: "Welsh",             native: "Cymraeg",     region: "Europe" },
  { code: "eu",     name: "Basque",            native: "Euskara",     region: "Europe" },
  { code: "ca",     name: "Catalan",           native: "Català",      region: "Europe" },
  { code: "gl",     name: "Galician",          native: "Galego",      region: "Europe" },
  { code: "mt",     name: "Maltese",           native: "Malti",       region: "Europe" },
  { code: "lb",     name: "Luxembourgish",     native: "Lëtzebuergesch", region: "Europe" },
  { code: "fy",     name: "Frisian",           native: "Frysk",       region: "Europe" },
  { code: "gd",     name: "Scottish Gaelic",   native: "Gàidhlig",    region: "Europe" },
  { code: "kw",     name: "Cornish",           native: "Kernewek",    region: "Europe" },
  { code: "br",     name: "Breton",            native: "Brezhoneg",   region: "Europe" },
  { code: "oc",     name: "Occitan",           native: "Occitan",     region: "Europe" },
  { code: "co",     name: "Corsican",          native: "Corsu",       region: "Europe" },
  { code: "sc",     name: "Sardinian",         native: "Sardu",       region: "Europe" },
  { code: "fo",     name: "Faroese",           native: "Føroyskt",    region: "Europe" },
  { code: "kl",     name: "Greenlandic",       native: "Kalaallisut", region: "Europe" },
  { code: "se",     name: "Northern Sami",     native: "Davvisámegiella", region: "Europe" },
  { code: "cnr",    name: "Montenegrin",       native: "Crnogorski",  region: "Europe" },
  { code: "rm",     name: "Romansh",           native: "Rumantsch",   region: "Europe" },
  { code: "an",     name: "Aragonese",         native: "Aragonés",    region: "Europe" },
  { code: "ast",    name: "Asturian",          native: "Asturianu",   region: "Europe" },
  { code: "wa",     name: "Walloon",           native: "Walon",       region: "Europe" },
  { code: "hsb",    name: "Upper Sorbian",     native: "Hornjoserbšćina", region: "Europe" },
  { code: "cv",     name: "Chuvash",           native: "Чӑвашла",     region: "Europe" },
  { code: "tt",     name: "Tatar",             native: "Татарча",     region: "Europe" },
  { code: "ba",     name: "Bashkir",           native: "Башҡортса",   region: "Europe" },
  { code: "sah",    name: "Yakut (Sakha)",     native: "Саха тыла",   region: "Europe" },


  // ── Africa ────────────────────────────────────────────────────────────
  { code: "sw",     name: "Swahili",           native: "Kiswahili",   region: "Africa" },
  { code: "am",     name: "Amharic",           native: "አማርኛ",       region: "Africa" },
  { code: "ha",     name: "Hausa",             native: "Hausa",       region: "Africa" },
  { code: "yo",     name: "Yoruba",            native: "Yorùbá",      region: "Africa" },
  { code: "ig",     name: "Igbo",              native: "Igbo",        region: "Africa" },
  { code: "zu",     name: "Zulu",              native: "isiZulu",     region: "Africa" },
  { code: "xh",     name: "Xhosa",             native: "isiXhosa",    region: "Africa" },
  { code: "af",     name: "Afrikaans",         native: "Afrikaans",   region: "Africa" },
  { code: "so",     name: "Somali",            native: "Soomaali",    region: "Africa" },
  { code: "rw",     name: "Kinyarwanda",       native: "Kinyarwanda", region: "Africa" },
  { code: "sn",     name: "Shona",             native: "chiShona",    region: "Africa" },
  { code: "mg",     name: "Malagasy",          native: "Malagasy",    region: "Africa" },
  { code: "st",     name: "Sesotho",           native: "Sesotho",     region: "Africa" },
  { code: "tn",     name: "Setswana",          native: "Setswana",    region: "Africa" },
  { code: "ss",     name: "Swazi",             native: "siSwati",     region: "Africa" },
  { code: "ve",     name: "Venda",             native: "Tshivenḓa",   region: "Africa" },
  { code: "ts",     name: "Tsonga",            native: "Xitsonga",    region: "Africa" },
  { code: "nr",     name: "Southern Ndebele",  native: "isiNdebele",  region: "Africa" },
  { code: "nso",    name: "Northern Sotho",    native: "Sepedi",      region: "Africa" },
  { code: "lg",     name: "Luganda",           native: "Luganda",     region: "Africa" },
  { code: "ln",     name: "Lingala",           native: "Lingála",     region: "Africa" },
  { code: "kg",     name: "Kongo",             native: "Kikongo",     region: "Africa" },
  { code: "lu",     name: "Luba-Katanga",      native: "Tshiluba",    region: "Africa" },
  { code: "ny",     name: "Chichewa",          native: "Chichewa",    region: "Africa" },
  { code: "ff",     name: "Fulah",             native: "Fulfulde",    region: "Africa" },
  { code: "wo",     name: "Wolof",             native: "Wolof",       region: "Africa" },
  { code: "bm",     name: "Bambara",           native: "Bamanankan",  region: "Africa" },
  { code: "ee",     name: "Ewe",               native: "Eʋegbe",      region: "Africa" },
  { code: "tw",     name: "Twi",               native: "Twi",         region: "Africa" },
  { code: "ak",     name: "Akan",              native: "Akan",        region: "Africa" },
  { code: "ti",     name: "Tigrinya",          native: "ትግርኛ",         region: "Africa" },
  { code: "om",     name: "Oromo",             native: "Afaan Oromoo", region: "Africa" },
  { code: "aa",     name: "Afar",              native: "Qafaraf",     region: "Africa" },
  { code: "ber",    name: "Berber (Tamazight)", native: "ⵜⴰⵎⴰⵣⵉⵖⵜ",  region: "Africa" },
  { code: "kab",    name: "Kabyle",            native: "Taqbaylit",   region: "Africa" },
  { code: "shi-Ma", name: "Tashelhit",         native: "ⵜⴰⵛⵍⵃⵉⵜ",     region: "Africa" },

  // ── Oceania ───────────────────────────────────────────────────────────
  { code: "mi",     name: "Maori",             native: "Māori",       region: "Oceania" },
  { code: "sm",     name: "Samoan",            native: "Gagana Samoa", region: "Oceania" },
  { code: "haw",    name: "Hawaiian",          native: "ʻŌlelo Hawaiʻi", region: "Oceania" },
  { code: "to",     name: "Tongan",            native: "Lea faka-Tonga", region: "Oceania" },
  { code: "fj",     name: "Fijian",            native: "Na Vosa Vakaviti", region: "Oceania" },
  { code: "ty",     name: "Tahitian",          native: "Reo Tahiti",  region: "Oceania" },
  { code: "mh",     name: "Marshallese",       native: "Kajin M̧ajeļ", region: "Oceania" },
  { code: "na",     name: "Nauruan",           native: "Dorerin Naoero", region: "Oceania" },
  { code: "ho",     name: "Hiri Motu",         native: "Hiri Motu",   region: "Oceania" },
  { code: "tpi",    name: "Tok Pisin",         native: "Tok Pisin",   region: "Oceania" },
  { code: "bi",     name: "Bislama",           native: "Bislama",     region: "Oceania" },
  { code: "ch",     name: "Chamorro",          native: "Chamoru",     region: "Oceania" },

  // ── Americas (Indigenous & regional) ──────────────────────────────────
  { code: "zh-CN",  name: "Chinese (Simplified)",  native: "简体中文", region: "Asia" },
  { code: "es-419", name: "Spanish (Latin America)", native: "Español (Latinoamérica)", region: "Americas" },
  { code: "en-NZ",  name: "English (New Zealand)", native: "English (NZ)", region: "Oceania" },
  { code: "en-US",  name: "English (US)",      native: "English (US)", region: "Americas" },
  { code: "en-GB",  name: "English (UK)",      native: "English (UK)", region: "Europe" },
  { code: "en-AU",  name: "English (Australia)", native: "English (AU)", region: "Oceania" },
  { code: "en-CA",  name: "English (Canada)",  native: "English (CA)", region: "Americas" },
  { code: "fr-CA",  name: "French (Canada)",   native: "Français (CA)", region: "Americas" },
  { code: "ht",     name: "Haitian Creole",    native: "Kreyòl Ayisyen", region: "Americas" },
  { code: "qu",     name: "Quechua",           native: "Runa Simi",   region: "Americas" },
  { code: "ay",     name: "Aymara",            native: "Aymar aru",   region: "Americas" },
  { code: "gn",     name: "Guarani",           native: "Avañe'ẽ",     region: "Americas" },
  { code: "nah",    name: "Nahuatl",           native: "Nāhuatl",     region: "Americas" },
  { code: "yua",    name: "Yucatec Maya",      native: "Màaya t'àan", region: "Americas" },
  { code: "quc",    name: "K'iche'",           native: "K'iche'",     region: "Americas" },
  { code: "arn",    name: "Mapudungun",        native: "Mapudungun",  region: "Americas" },
  { code: "nv",     name: "Navajo",            native: "Diné Bizaad", region: "Americas" },
  { code: "chr",    name: "Cherokee",          native: "ᏣᎳᎩ",         region: "Americas" },
  { code: "iu",     name: "Inuktitut",         native: "ᐃᓄᒃᑎᑐᑦ",       region: "Americas" },
  { code: "cr",     name: "Cree",              native: "ᓀᐦᐃᔭᐍᐏᐣ",     region: "Americas" },
  { code: "oj",     name: "Ojibwe",            native: "Anishinaabemowin", region: "Americas" },
  { code: "eo",     name: "Esperanto",         native: "Esperanto",   region: "Europe" },

];

export const LANGUAGES_TUPLE: [string, string][] = LANGUAGES.map((l) => [l.code, l.name]);

export const LANG_BY_CODE: Record<string, Language> = Object.fromEntries(
  LANGUAGES.map((l) => [l.code, l]),
);

export const langName = (code: string) => LANG_BY_CODE[code]?.name ?? code;

/** Fuzzy-ish search across code, English name, native name. */
export function searchLanguages(query: string, pool: Language[] = LANGUAGES): Language[] {
  const q = query.trim().toLowerCase();
  if (!q) return pool;
  return pool.filter((l) => {
    const hay = `${l.code} ${l.name} ${l.native ?? ""} ${l.region ?? ""}`.toLowerCase();
    return hay.includes(q);
  });
}

export function isIndianLanguage(lang: string | null | undefined): boolean {
  if (!lang) return false;
  const l = lang.toLowerCase().trim();
  const base = l.split("-")[0];
  const item = LANG_BY_CODE[lang] || LANG_BY_CODE[l] || LANG_BY_CODE[base];
  if (item?.region === "India") return true;

  const byName = LANGUAGES.find((x) => x.name.toLowerCase() === l || (x.native && x.native.toLowerCase() === l));
  if (byName?.region === "India") return true;

  const indianCodes = new Set([
    "hi", "bn", "kn", "ml", "mr", "od", "or", "pa", "ta", "te", "gu",
    "ur", "as", "sa", "bho", "mai", "awa", "raj", "kok", "sd", "ks", "ne",
    "kfa", "beo", "bfq", "mbf", "hlb", "spv", "sjp", "swv", "wtm", "mpt",
    "noe", "bfy", "him", "gbm", "kum", "anp", "bnd", "mni", "sat", "doi",
    "brx", "mag", "hne", "gom", "tcy", "kha", "lus", "grt", "nag", "sck",
    "gon", "kru", "mwr", "bpy", "lep",
    "hindi", "bengali", "tamil", "telugu", "marathi", "gujarati", "kannada",
    "malayalam", "punjabi", "urdu", "odia", "assamese", "bhojpuri", "rajasthani",
    "sanskrit", "maithili", "konkani",
    "hinglish", "tanglish", "teluglish", "minglish", "gujlish", "kanglish", "manglish", "punglish"
  ]);
  return indianCodes.has(l) || indianCodes.has(base) || l.endsWith("-in");
}

