const fs = require('fs');

const kalakarCatalog = [
  {
    id: "builtin-lala",
    name: "Lala",
    feature: "Multi-color word highlight, casual script style",
    font: "Outfit",
    weight: 800,
    size: 46,
    textCase: "normal",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 2.5 },
    shadow: { on: true, color: "#000000", opacity: 80, x: 0, y: 4, blur: 8 },
    activeWord: { color: "#F97316", scale: 1.18 },
    posY: 80,
    chunk: 3,
    trans: "pop",
    speed: 100,
  },
  {
    id: "builtin-ali-abdaal",
    name: "Ali Abdaal",
    feature: "Clean sans-serif, subtle active word accent",
    font: "Inter",
    weight: 600,
    size: 38,
    textCase: "normal",
    color: "#F8FAFC",
    bg: { on: true, color: "rgba(0, 0, 0, 0.75)", opacity: 80, radius: 8, padX: 14, padY: 6 },
    activeWord: { color: "#38BDF8", scale: 1.05 },
    posY: 82,
    chunk: 3,
    trans: "fade",
    speed: 150,
  },
  {
    id: "builtin-double-trouble",
    name: "Double Trouble",
    feature: "Dual word highlight box animation",
    font: "Montserrat",
    weight: 900,
    size: 46,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 3 },
    activeWord: { color: "#000000", bgOn: true, bgColor: "#FFE600", scale: 1.15 },
    posY: 78,
    chunk: 2,
    trans: "pop",
    speed: 95,
  },
  {
    id: "builtin-delhi",
    name: "Delhi",
    feature: "Bold uppercase, vibrant yellow & neon accent",
    font: "Plus Jakarta Sans",
    weight: 800,
    size: 48,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 3 },
    shadow: { on: true, color: "#000000", opacity: 90, x: 0, y: 5, blur: 10 },
    activeWord: { color: "#FF9933", scale: 1.2 },
    posY: 78,
    chunk: 2,
    trans: "pop",
    speed: 90,
  },
  {
    id: "builtin-kalakar-motion",
    name: "Kalakar Motion",
    feature: "Dynamic motion pop-in effect",
    font: "Montserrat",
    weight: 900,
    size: 48,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 3.5 },
    shadow: { on: true, color: "#000000", opacity: 90, x: 0, y: 6, blur: 12 },
    activeWord: { color: "#F59E0B", scale: 1.24 },
    posY: 76,
    chunk: 2,
    trans: "pop",
    speed: 80,
  },
  {
    id: "builtin-kathmandu",
    name: "Kathmandu",
    feature: "Lowercase minimal, Bold, Shadow",
    font: "Inter",
    weight: 800,
    size: 40,
    textCase: "lower",
    color: "#F8FAFC",
    shadow: { on: true, color: "#000000", opacity: 75, x: 0, y: 3, blur: 8 },
    activeWord: { color: "#2DD4BF", scale: 1.12 },
    posY: 82,
    chunk: 3,
    trans: "fade",
    speed: 120,
  },
  {
    id: "builtin-bubble-style",
    name: "Bubbles",
    feature: "Rounded pill background pop",
    font: "Bangers",
    weight: 800,
    size: 52,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 5 },
    shadow: { on: true, color: "#000000", opacity: 95, x: 3, y: 3, blur: 0 },
    activeWord: { color: "#FFE600", scale: 1.25 },
    posY: 78,
    chunk: 2,
    trans: "bounce",
    speed: 110,
  },
  {
    id: "builtin-ij-template",
    name: "IJ Template",
    feature: "Irfan Junejo signature style with custom primary color & blur adjustment",
    font: "Inter",
    weight: 700,
    size: 42,
    textCase: "upper",
    color: "#FFFBEB",
    stroke: { on: true, color: "rgba(0,0,0,0.85)", width: 2 },
    shadow: { on: true, color: "#000000", opacity: 80, x: 0, y: 4, blur: 12 },
    activeWord: { color: "#F59E0B", scale: 1.15 },
    posY: 80,
    chunk: 3,
    trans: "fade",
    speed: 160,
  },
  {
    id: "builtin-kalakar-glow",
    name: "Kalakar Glow",
    feature: "Neon text glow, Bold, Shadow",
    font: "Space Grotesk",
    weight: 800,
    size: 46,
    textCase: "upper",
    color: "#FFFFFF",
    glow: { on: true, color: "#00F0FF", blur: 20, int: 90 },
    stroke: { on: true, color: "#000000", width: 2.5 },
    activeWord: { color: "#67E8F9", scale: 1.18 },
    posY: 78,
    chunk: 2,
    trans: "pop",
    speed: 95,
  },
  {
    id: "builtin-clean-motion",
    name: "Clean Motion",
    feature: "Smooth word-by-word motion (Free Render)",
    font: "Inter",
    weight: 700,
    size: 40,
    textCase: "normal",
    color: "#FFFFFF",
    shadow: { on: true, color: "#000000", opacity: 60, x: 0, y: 2, blur: 6 },
    activeWord: { color: "#E0E7FF", scale: 1.08 },
    posY: 82,
    chunk: 3,
    trans: "slide-up",
    speed: 140,
  },
  {
    id: "builtin-goa",
    name: "Goa",
    feature: "Tropical contrast colors, Bold, Shadow",
    font: "Montserrat",
    weight: 800,
    size: 46,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 3 },
    shadow: { on: true, color: "#000000", opacity: 85, x: 0, y: 4, blur: 10 },
    activeWord: { color: "#F43F5E", scale: 1.2 },
    posY: 78,
    chunk: 2,
    trans: "pop",
    speed: 95,
  },
  {
    id: "builtin-islamabad",
    name: "Islamabad",
    feature: "Italic serif accent, Shadow",
    font: "Playfair Display",
    weight: 700,
    size: 42,
    textCase: "title",
    color: "#FFFFFF",
    shadow: { on: true, color: "#000000", opacity: 80, x: 0, y: 3, blur: 8 },
    activeWord: { color: "#F59E0B", scale: 1.1 },
    posY: 82,
    chunk: 3,
    trans: "fade",
    speed: 180,
  },
  {
    id: "builtin-mumbai",
    name: "Mumbai",
    feature: "High-contrast yellow/cyan accent, Bold, Shadow",
    font: "Bebas Neue",
    weight: 900,
    size: 52,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 3.5 },
    shadow: { on: true, color: "#000000", opacity: 90, x: 0, y: 5, blur: 10 },
    activeWord: { color: "#FACC15", scale: 1.22 },
    posY: 78,
    chunk: 2,
    trans: "pop",
    speed: 90,
  },
  {
    id: "builtin-karachi",
    name: "Karachi",
    feature: "Stacked vertical line pop, Shadow",
    font: "Anton",
    weight: 900,
    size: 50,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 4 },
    shadow: { on: true, color: "#000000", opacity: 95, x: 0, y: 6, blur: 12 },
    activeWord: { color: "#EF4444", scale: 1.25 },
    posY: 76,
    chunk: 2,
    trans: "pop",
    speed: 85,
  },
  {
    id: "builtin-shamani",
    name: "Shamani",
    feature: "Raj Shamani signature style, spaced uppercase",
    font: "Montserrat",
    weight: 800,
    size: 44,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 2.5 },
    shadow: { on: true, color: "#000000", opacity: 90, x: 0, y: 4, blur: 10 },
    activeWord: { color: "#FFE600", scale: 1.2 },
    posY: 80,
    chunk: 2,
    trans: "pop",
    speed: 90,
  },
  {
    id: "builtin-shamani-2",
    name: "Shamani 2",
    feature: "Raj Shamani double-stacked repetition style",
    font: "Anton",
    weight: 900,
    size: 52,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 4 },
    shadow: { on: true, color: "#000000", opacity: 100, x: 0, y: 6, blur: 14 },
    activeWord: { color: "#F59E0B", scale: 1.25 },
    posY: 76,
    chunk: 2,
    trans: "pop",
    speed: 85,
  },
  {
    id: "builtin-flicker",
    name: "Flicker",
    feature: "Rapid text flicker animation effect",
    font: "Space Grotesk",
    weight: 800,
    size: 46,
    textCase: "upper",
    color: "#FFFFFF",
    glow: { on: true, color: "#00F0FF", blur: 14, int: 85 },
    stroke: { on: true, color: "#000000", width: 2 },
    activeWord: { color: "#00F0FF", scale: 1.15 },
    posY: 80,
    chunk: 2,
    trans: "typewriter",
    speed: 75,
  },
  {
    id: "builtin-underline",
    name: "Underline",
    feature: "Animated underline accent on spoken word",
    font: "Inter",
    weight: 700,
    size: 42,
    textCase: "normal",
    color: "#FFFFFF",
    shadow: { on: true, color: "#000000", opacity: 70, x: 0, y: 3, blur: 6 },
    activeWord: { color: "#38BDF8", scale: 1.1 },
    posY: 82,
    chunk: 3,
    trans: "fade",
    speed: 120,
  },
  {
    id: "builtin-green-pop",
    name: "Pop Up",
    feature: "Scale pop-up animation, Bold, Shadow",
    font: "Anton",
    weight: 900,
    size: 50,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 4 },
    shadow: { on: true, color: "#000000", opacity: 90, x: 0, y: 6, blur: 12 },
    activeWord: { color: "#10B981", scale: 1.25 },
    posY: 78,
    chunk: 2,
    trans: "pop",
    speed: 85,
  },
  {
    id: "builtin-dhaka",
    name: "Dhaka",
    feature: "Classic subtitle layout, Bold, Shadow",
    font: "Poppins",
    weight: 700,
    size: 42,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 2.5 },
    shadow: { on: true, color: "#000000", opacity: 85, x: 0, y: 4, blur: 8 },
    activeWord: { color: "#EAB308", scale: 1.16 },
    posY: 80,
    chunk: 3,
    trans: "pop",
    speed: 100,
  },
  {
    id: "builtin-kalakar-shadow",
    name: "Kalakar Shadow",
    feature: "Deep drop shadow, high contrast readability",
    font: "Montserrat",
    weight: 900,
    size: 46,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 3 },
    shadow: { on: true, color: "#000000", opacity: 95, x: 0, y: 6, blur: 14 },
    activeWord: { color: "#FACC15", scale: 1.15 },
    posY: 80,
    chunk: 2,
    trans: "pop",
    speed: 100,
  },
  {
    id: "builtin-kalakar",
    name: "Kalakar",
    feature: "Standard original Kalakar subtitle style",
    font: "Plus Jakarta Sans",
    weight: 800,
    size: 46,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 2.5 },
    shadow: { on: true, color: "#000000", opacity: 85, x: 0, y: 4, blur: 8 },
    activeWord: { color: "#F59E0B", scale: 1.16 },
    posY: 79,
    chunk: 2,
    trans: "pop",
    speed: 90,
  },
  {
    id: "builtin-hormozi-style",
    name: "Hormozi Style",
    feature: "Alex Hormozi style (Impact font, yellow/green highlight, shadow)",
    font: "Anton",
    weight: 900,
    size: 50,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 4.5 },
    shadow: { on: true, color: "#000000", opacity: 95, x: 0, y: 6, blur: 12 },
    activeWord: { color: "#FFE600", scale: 1.25 },
    posY: 78,
    chunk: 2,
    trans: "pop",
    speed: 90,
  },
  {
    id: "builtin-editing-skool",
    name: "Editing Skool",
    feature: "Signature Editing Skool style (Free Render)",
    font: "Montserrat",
    weight: 900,
    size: 46,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 3 },
    activeWord: { color: "#000000", bgOn: true, bgColor: "#00F0FF", scale: 1.15 },
    posY: 78,
    chunk: 2,
    trans: "pop",
    speed: 95,
  },
  {
    id: "builtin-mr-beast-style-1",
    name: "Mr Beast Style 1",
    feature: "Large impact font, yellow highlight, shadow",
    font: "Anton",
    weight: 900,
    size: 52,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 4 },
    shadow: { on: true, color: "#000000", opacity: 90, x: 0, y: 6, blur: 10 },
    activeWord: { color: "#FFE600", bgOn: true, bgColor: "#DC2626", scale: 1.22 },
    posY: 76,
    chunk: 2,
    trans: "pop",
    speed: 85,
  },
  {
    id: "builtin-mr-beast-style-2",
    name: "Mr Beast Style 2",
    feature: "Rotated text with thick stroke & shadow",
    font: "Archivo Black",
    weight: 900,
    size: 50,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 4.5 },
    shadow: { on: true, color: "#000000", opacity: 90, x: 0, y: 6, blur: 10 },
    activeWord: { color: "#22C55E", scale: 1.24 },
    posY: 76,
    chunk: 2,
    trans: "pop",
    speed: 90,
  },
  {
    id: "builtin-iman-gadzhi",
    name: "Iman Gadzhi",
    feature: "Luxury minimalist editorial style",
    font: "EB Garamond",
    weight: 700,
    size: 42,
    textCase: "title",
    color: "#FFFBEB",
    glow: { on: true, color: "#D4AF37", blur: 14, int: 70 },
    bg: { on: true, color: "rgba(15, 15, 20, 0.75)", opacity: 80, radius: 6, padX: 16, padY: 6 },
    activeWord: { color: "#FCD34D", scale: 1.08 },
    posY: 82,
    chunk: 3,
    trans: "fade",
    speed: 180,
  },
  {
    id: "builtin-devin-jatho",
    name: "Devin Jatho",
    feature: "Creator style with sharp shadow drop",
    font: "Space Grotesk",
    weight: 800,
    size: 46,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#00F0FF", width: 2.5 },
    shadow: { on: true, color: "#EC4899", opacity: 80, x: 0, y: 0, blur: 12 },
    activeWord: { color: "#EC4899", scale: 1.18 },
    posY: 78,
    chunk: 2,
    trans: "pop",
    speed: 95,
  },
  {
    id: "builtin-highlighted-word",
    name: "Highlighted Word",
    feature: "Solid background box highlight on active word",
    font: "Inter",
    weight: 800,
    size: 44,
    textCase: "upper",
    color: "#94A3B8",
    stroke: { on: true, color: "#000000", width: 2.5 },
    activeWord: { color: "#22C55E", scale: 1.16 },
    posY: 80,
    chunk: 3,
    trans: "pop",
    speed: 90,
  },
  {
    id: "builtin-clean-glow-style",
    name: "Clean Glow Style",
    feature: "Soft outline glow effect, Shadow",
    font: "Outfit",
    weight: 700,
    size: 42,
    textCase: "upper",
    color: "#FFFFFF",
    glow: { on: true, color: "#00F0FF", blur: 16, int: 80 },
    stroke: { on: true, color: "#000000", width: 2 },
    activeWord: { color: "#67E8F9", scale: 1.12 },
    posY: 80,
    chunk: 2,
    trans: "pop",
    speed: 100,
  },
  {
    id: "builtin-kalakar-clean",
    name: "Kalakar Clean",
    feature: "Ultra-clean minimal subtitle overlay",
    font: "DM Sans",
    weight: 700,
    size: 40,
    textCase: "normal",
    color: "#FFFFFF",
    shadow: { on: true, color: "#000000", opacity: 70, x: 0, y: 3, blur: 6 },
    activeWord: { color: "#F59E0B", scale: 1.1 },
    posY: 82,
    chunk: 3,
    trans: "pop",
    speed: 110,
  },
  {
    id: "builtin-black-punch",
    name: "Black Punch",
    feature: "Solid black punch box background",
    font: "Archivo Black",
    weight: 900,
    size: 48,
    textCase: "upper",
    color: "#000000",
    stroke: { on: true, color: "#FFFFFF", width: 3.5 },
    shadow: { on: true, color: "#000000", opacity: 90, x: 0, y: 4, blur: 10 },
    activeWord: { color: "#FFE600", scale: 1.2 },
    posY: 78,
    chunk: 2,
    trans: "pop",
    speed: 90,
  },
  {
    id: "builtin-kalakar-word",
    name: "Kalakar Word",
    feature: "One word at a time mode (Free Render)",
    font: "Poppins",
    weight: 900,
    size: 52,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 3.5 },
    shadow: { on: true, color: "#000000", opacity: 90, x: 0, y: 5, blur: 12 },
    activeWord: { color: "#F59E0B", scale: 1.24 },
    posY: 78,
    chunk: 1,
    trans: "pop",
    speed: 80,
  },
  {
    id: "builtin-pixelated-word",
    name: "Pixelated Word",
    feature: "Retro 8-bit arcade font effect",
    font: "Press Start 2P",
    weight: 400,
    size: 32,
    textCase: "upper",
    color: "#10B981",
    glow: { on: true, color: "#10B981", blur: 14, int: 85 },
    shadow: { on: true, color: "#000000", opacity: 100, x: 3, y: 3, blur: 0 },
    activeWord: { color: "#34D399", scale: 1.15 },
    posY: 80,
    chunk: 2,
    trans: "pop",
    speed: 120,
  },
  {
    id: "builtin-ziada",
    name: "Ziada",
    feature: "High impact bold Hindi/Urdu content style",
    font: "Archivo Black",
    weight: 900,
    size: 50,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#EA580C", width: 4 },
    shadow: { on: true, color: "#000000", opacity: 95, x: 0, y: 6, blur: 12 },
    activeWord: { color: "#F97316", scale: 1.24 },
    posY: 76,
    chunk: 2,
    trans: "pop",
    speed: 90,
  },
  {
    id: "builtin-liquid-glass",
    name: "Liquid Glass",
    feature: "Frosted glass text background effect",
    font: "Inter",
    weight: 600,
    size: 38,
    textCase: "normal",
    color: "#F8FAFC",
    bg: { on: true, color: "rgba(255, 255, 255, 0.16)", opacity: 85, radius: 12, padX: 16, padY: 8 },
    shadow: { on: true, color: "#000000", opacity: 50, x: 0, y: 4, blur: 12 },
    activeWord: { color: "#38BDF8", scale: 1.08 },
    posY: 82,
    chunk: 3,
    trans: "fade",
    speed: 140,
  },
  {
    id: "builtin-top-up",
    name: "Top Up",
    feature: "Slide-up entrance animation, Bold, Shadow",
    font: "Montserrat",
    weight: 800,
    size: 44,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 3 },
    shadow: { on: true, color: "#000000", opacity: 85, x: 0, y: 4, blur: 10 },
    activeWord: { color: "#22C55E", scale: 1.2 },
    posY: 78,
    chunk: 2,
    trans: "slide-up",
    speed: 100,
  },
  {
    id: "builtin-mota",
    name: "Mota",
    feature: "Extra thick heavy typography, Shadow",
    font: "Archivo Black",
    weight: 900,
    size: 54,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#000000", width: 5 },
    shadow: { on: true, color: "#000000", opacity: 100, x: 0, y: 8, blur: 16 },
    activeWord: { color: "#FFE600", scale: 1.28 },
    posY: 76,
    chunk: 2,
    trans: "pop",
    speed: 85,
  },
  {
    id: "builtin-tabahi",
    name: "Tabahi",
    feature: "High-energy explosive style, Shadow",
    font: "Anton",
    weight: 900,
    size: 52,
    textCase: "upper",
    color: "#FFFFFF",
    stroke: { on: true, color: "#DC2626", width: 4 },
    shadow: { on: true, color: "#000000", opacity: 95, x: 0, y: 6, blur: 14 },
    activeWord: { color: "#EF4444", scale: 1.26 },
    posY: 76,
    chunk: 2,
    trans: "bounce",
    speed: 85,
  },
  {
    id: "builtin-deep-glow",
    name: "Deep Glow",
    feature: "Multi-pass neon glow bloom effect",
    font: "Montserrat",
    weight: 800,
    size: 46,
    textCase: "upper",
    color: "#FFFFFF",
    glow: { on: true, color: "#8B5CF6", blur: 24, int: 90 },
    stroke: { on: true, color: "#000000", width: 2.5 },
    activeWord: { color: "#C084FC", scale: 1.18 },
    posY: 78,
    chunk: 2,
    trans: "pop",
    speed: 100,
  },
  {
    id: "builtin-seedha-saadha",
    name: "Seedha Saadha",
    feature: "Simple straight subtitle, minimal shadow",
    font: "Inter",
    weight: 600,
    size: 38,
    textCase: "normal",
    color: "#F8FAFC",
    shadow: { on: true, color: "#000000", opacity: 55, x: 0, y: 2, blur: 6 },
    activeWord: { color: "#FFFFFF", scale: 1.05 },
    posY: 82,
    chunk: 3,
    trans: "fade",
    speed: 160,
  },
  {
    id: "builtin-thora-cinematic",
    name: "Thora Cinematic",
    feature: "Widescreen movie subtitle aesthetic",
    font: "Playfair Display",
    weight: 700,
    size: 40,
    textCase: "title",
    color: "#FFFFFF",
    shadow: { on: true, color: "#000000", opacity: 75, x: 0, y: 3, blur: 8 },
    activeWord: { color: "#FDE047", scale: 1.08 },
    posY: 84,
    chunk: 3,
    trans: "fade",
    speed: 200,
  },
  {
    id: "builtin-zero-gravity",
    name: "Zero Gravity",
    feature: "Floating animation effect",
    font: "Space Grotesk",
    weight: 800,
    size: 46,
    textCase: "upper",
    color: "#FFFFFF",
    glow: { on: true, color: "#3B82F6", blur: 16, int: 80 },
    stroke: { on: true, color: "#000000", width: 2 },
    activeWord: { color: "#60A5FA", scale: 1.2 },
    posY: 78,
    chunk: 2,
    trans: "bounce",
    speed: 120,
  },
];

console.log('Total Kalakar templates to build:', kalakarCatalog.length);

const presetsCode = kalakarCatalog.map((t) => {
  const patch = {
    fontFamily: `font("${t.font}")`,
    fontWeight: t.weight,
    fontSize: t.size,
    textCase: `"${t.textCase}"`,
    color: `"${t.color}"`,
    posY: t.posY,
    wordsPerChunk: t.chunk,
    transition: `"${t.trans}"`,
    transitionSpeed: t.speed,
  };

  if (t.stroke) {
    patch.strokeOn = t.stroke.on;
    patch.strokeColor = `"${t.stroke.color}"`;
    patch.strokeWidth = t.stroke.width;
  }
  if (t.shadow) {
    patch.shadowOn = t.shadow.on;
    patch.shadowColor = `"${t.shadow.color}"`;
    patch.shadowOpacity = t.shadow.opacity;
    patch.shadowX = t.shadow.x;
    patch.shadowY = t.shadow.y;
    patch.shadowBlur = t.shadow.blur;
  }
  if (t.glow) {
    patch.glowOn = t.glow.on;
    patch.glowColor = `"${t.glow.color}"`;
    patch.glowBlur = t.glow.blur;
    patch.glowIntensity = t.glow.int;
  }
  if (t.bg) {
    patch.bgOn = t.bg.on;
    patch.bgColor = `"${t.bg.color}"`;
    patch.bgOpacity = t.bg.opacity;
    patch.bgRadius = t.bg.radius;
    patch.bgPadX = t.bg.padX;
    patch.bgPadY = t.bg.padY;
  }
  if (t.activeWord) {
    patch.activeWordOn = true;
    patch.activeWordColor = `"${t.activeWord.color}"`;
    patch.activeWordScale = t.activeWord.scale;
    if (t.activeWord.bgOn) {
      patch.activeWordBgOn = true;
      patch.activeWordBgColor = `"${t.activeWord.bgColor}"`;
    }
  }

  const patchLines = Object.entries(patch).map(([k, v]) => `      ${k}: ${v},`).join('\n');

  return `  {
    id: "${t.id}",
    name: "Kalakar · ${t.name}",
    cleanName: "${t.name}",
    category: "Kalakar",
    feature: "${t.feature}",
    isBehindYou: false,
    isNew: false,
    patch: {
${patchLines}
    }
  }`;
});

const tsContent = `// All 43 Caption Templates extracted from Kalakar (https://app.kalakar.io)
// Pixel-accurate recreation with typography, animations, word highlights, strokes, and glows.
import type { CapStyle } from "./captionStyle";

const FONT_MAP: Record<string, string> = {
  "Inter": "'Inter', system-ui, sans-serif",
  "Poppins": "'Poppins', 'Inter', sans-serif",
  "Montserrat": "'Montserrat', 'Inter', sans-serif",
  "Space Grotesk": "'Space Grotesk', 'Inter', sans-serif",
  "DM Sans": "'DM Sans', 'Inter', sans-serif",
  "Outfit": "'Outfit', 'Inter', sans-serif",
  "Anton": "'Anton', 'Impact', sans-serif",
  "Archivo Black": "'Archivo Black', 'Impact', sans-serif",
  "Bebas Neue": "'Bebas Neue', 'Impact', sans-serif",
  "Bangers": "'Bangers', 'Impact', cursive",
  "Permanent Marker": "'Permanent Marker', cursive",
  "Press Start 2P": "'Press Start 2P', ui-monospace, monospace",
  "EB Garamond": "'EB Garamond', Georgia, serif",
  "Playfair Display": "'Playfair Display', Georgia, serif",
  "DM Serif Display": "'DM Serif Display', Georgia, serif",
  "Special Elite": "'Special Elite', ui-monospace, monospace",
  "Work Sans": "'Work Sans', 'Inter', sans-serif",
  "Oswald": "'Oswald', 'Impact', sans-serif",
  "Black Ops One": "'Black Ops One', 'Impact', sans-serif",
  "Plus Jakarta Sans": "'Plus Jakarta Sans', 'Inter', sans-serif",
};

const font = (label: string): string => FONT_MAP[label] ?? \`'\${label}', system-ui, sans-serif\`;

export interface KalakarPresetItem {
  id: string;
  name: string;
  cleanName: string;
  category: "Kalakar";
  feature?: string;
  isBehindYou?: boolean;
  isNew?: boolean;
  patch: Partial<CapStyle>;
}

export const KALAKAR_43_PRESETS: KalakarPresetItem[] = [
` + presetsCode.join(',\n') + `
];
`;

fs.writeFileSync('src/lib/kalakarPresets.ts', tsContent, 'utf8');
console.log('Successfully written src/lib/kalakarPresets.ts with 43 templates!');
