export const CAPTIK_72_PRESETS: { name: string; patch: Partial<CapStyle>; category?: string }[] = [
  {
    name: "Captik · Captik Glow",
    category: "Popular",
    patch: {
      fontFamily: font('Space Grotesk'),
      fontWeight: 800,
      fontSize: 46,
      textCase: 'upper',
      color: '#FFFFFF',
      glowOn: true,
      glowColor: '#F59E0B',
      glowBlur: 16,
      glowIntensity: 85,
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 2.5,
      posY: 78,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 95,
      activeWordOn: true,
      activeWordColor: '#FCD34D',
      activeWordScale: 1.18,
    }
  },
  {
    name: "Captik · Ali Abdaal",
    category: "Clean",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 600,
      fontSize: 38,
      textCase: 'normal',
      color: '#F1F5F9',
      bgOn: true,
      bgColor: 'rgba(0, 0, 0, 0.72)',
      bgOpacity: 80,
      bgRadius: 8,
      bgPadX: 14,
      bgPadY: 6,
      posY: 82,
      wordsPerChunk: 3,
      transition: 'fade',
      transitionSpeed: 160,
      activeWordOn: true,
      activeWordColor: '#38BDF8',
      activeWordScale: 1.05,
    }
  },
  {
    name: "Captik · Captik Shadow",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Captik",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Clean Motion",
    category: "Clean",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 600,
      fontSize: 38,
      textCase: 'normal',
      color: '#F1F5F9',
      bgOn: true,
      bgColor: 'rgba(0, 0, 0, 0.72)',
      bgOpacity: 80,
      bgRadius: 8,
      bgPadX: 14,
      bgPadY: 6,
      posY: 82,
      wordsPerChunk: 3,
      transition: 'fade',
      transitionSpeed: 160,
      activeWordOn: true,
      activeWordColor: '#38BDF8',
      activeWordScale: 1.05,
    }
  },
  {
    name: "Captik · Bubble Style",
    category: "Bold & animated",
    patch: {
      fontFamily: font('Fredoka'),
      fontWeight: 700,
      fontSize: 44,
      textCase: 'normal',
      color: '#1E1B4B',
      bgOn: true,
      bgColor: '#FEF08A',
      bgRadius: 24,
      bgPadX: 18,
      bgPadY: 8,
      posY: 78,
      wordsPerChunk: 3,
      transition: 'bounce',
      transitionSpeed: 110,
      activeWordOn: true,
      activeWordColor: '#4338CA',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Hormozi Style",
    category: "Bold & animated",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 50,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 4.5,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 95,
      shadowX: 0,
      shadowY: 5,
      shadowBlur: 10,
      posY: 78,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.25,
      impactWordsRed: 'money, profit, secret, free, never, viral',
      impactRedColor: '#EF4444',
    }
  },
  {
    name: "Captik · Editing Skool",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Mr Beast Style 1",
    category: "Bold & animated",
    patch: {
      fontFamily: font('Impact'),
      fontWeight: 900,
      fontSize: 52,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 0,
      posY: 76,
      wordsPerChunk: 2,
      transition: 'bounce',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordBgOn: true,
      activeWordBgColor: '#00F0FF',
      activeWordColor: '#000000',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Mr Beast Style 2",
    category: "Popular",
    patch: {
      fontFamily: font('Impact'),
      fontWeight: 900,
      fontSize: 52,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 5,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 100,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 0,
      posY: 76,
      wordsPerChunk: 2,
      transition: 'bounce',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordBgOn: true,
      activeWordBgColor: '#FFE600',
      activeWordColor: '#000000',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Iman Gadzhi",
    category: "Popular",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      letterSpacing: 2,
      color: '#FAF5E9',
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 3,
      shadowBlur: 12,
      posY: 52,
      wordsPerChunk: 2,
      transition: 'fade',
      transitionSpeed: 180,
      activeWordOn: true,
      activeWordColor: '#D4AF37',
      activeWordScale: 1.08,
    }
  },
  {
    name: "Captik · Devin Jatho",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Highlighted Word",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Clean Glow Style",
    category: "Clean",
    patch: {
      fontFamily: font('Space Grotesk'),
      fontWeight: 800,
      fontSize: 46,
      textCase: 'upper',
      color: '#FFFFFF',
      glowOn: true,
      glowColor: '#F59E0B',
      glowBlur: 16,
      glowIntensity: 85,
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 2.5,
      posY: 78,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 95,
      activeWordOn: true,
      activeWordColor: '#FCD34D',
      activeWordScale: 1.18,
    }
  },
  {
    name: "Captik · Captik Clean",
    category: "Clean",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 600,
      fontSize: 38,
      textCase: 'normal',
      color: '#F1F5F9',
      bgOn: true,
      bgColor: 'rgba(0, 0, 0, 0.72)',
      bgOpacity: 80,
      bgRadius: 8,
      bgPadX: 14,
      bgPadY: 6,
      posY: 82,
      wordsPerChunk: 3,
      transition: 'fade',
      transitionSpeed: 160,
      activeWordOn: true,
      activeWordColor: '#38BDF8',
      activeWordScale: 1.05,
    }
  },
  {
    name: "Captik · Black Punch",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Captik Word",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Pixelated Word",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Liquid Glass",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Tabahi",
    category: "Popular",
    patch: {
      fontFamily: font('Poppins'),
      fontWeight: 800,
      fontSize: 46,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 85,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 10,
      posY: 78,
      wordsPerChunk: 3,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#22C55E',
      activeWordScale: 1.18,
    }
  },
  {
    name: "Captik · Deep Glow",
    category: "Popular",
    patch: {
      fontFamily: font('Space Grotesk'),
      fontWeight: 800,
      fontSize: 46,
      textCase: 'upper',
      color: '#FFFFFF',
      glowOn: true,
      glowColor: '#F59E0B',
      glowBlur: 16,
      glowIntensity: 85,
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 2.5,
      posY: 78,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 95,
      activeWordOn: true,
      activeWordColor: '#FCD34D',
      activeWordScale: 1.18,
    }
  },
  {
    name: "Captik · Seedha Saadha",
    category: "Popular",
    patch: {
      fontFamily: font('Poppins'),
      fontWeight: 800,
      fontSize: 46,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 85,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 10,
      posY: 78,
      wordsPerChunk: 3,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#22C55E',
      activeWordScale: 1.18,
    }
  },
  {
    name: "Captik · Thora Cinematic",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Delhi",
    category: "Popular",
    patch: {
      fontFamily: font('Poppins'),
      fontWeight: 800,
      fontSize: 46,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 85,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 10,
      posY: 78,
      wordsPerChunk: 3,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#22C55E',
      activeWordScale: 1.18,
    }
  },
  {
    name: "Captik · Illusion",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Editor Masala",
    category: "Popular",
    patch: {
      fontFamily: font('Poppins'),
      fontWeight: 800,
      fontSize: 46,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3.5,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 85,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 10,
      posY: 78,
      wordsPerChunk: 3,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FF9933',
      activeWordScale: 1.18,
    }
  },
  {
    name: "Captik · Aura",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Swiss",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Big Reveal",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · The Big Red",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Scribble",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Archives",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Blockbuster",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Journal",
    category: "Clean",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Interlock",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Anchorage",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Beacon",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#F59E0B',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Cove",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Driftwood",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Ellis",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Ferrier",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Garnet",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#EF4444',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Hawser",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Ibis",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Jetty",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Keel",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Lanyard",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Mizzen",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Netting",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Outhaul",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Painter",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Quay",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Rudder",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Scupper",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Taffrail",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Underway",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Vang",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Windlass",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Yawl",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Abbey",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Belfry",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Cloister",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Dovecote",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Effigy",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Font",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Gable",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Hassock",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Iron",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Jamb",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Keystone",
    category: "Popular",
    patch: {
      fontFamily: font('Inter'),
      fontWeight: 800,
      fontSize: 44,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 80,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 8,
      posY: 80,
      wordsPerChunk: 2,
      transition: 'pop',
      transitionSpeed: 100,
      activeWordOn: true,
      activeWordColor: '#FACC15',
      activeWordScale: 1.15,
    }
  },
  {
    name: "Captik · Lintel",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
  {
    name: "Captik · Mullion",
    category: "Behind you",
    patch: {
      fontFamily: font('Montserrat'),
      fontWeight: 900,
      fontSize: 54,
      textCase: 'upper',
      color: '#FFFFFF',
      strokeOn: true,
      strokeColor: '#000000',
      strokeWidth: 3,
      shadowOn: true,
      shadowColor: '#000000',
      shadowOpacity: 90,
      shadowX: 0,
      shadowY: 4,
      shadowBlur: 14,
      posY: 42,
      wordsPerChunk: 1,
      transition: 'pop',
      transitionSpeed: 90,
      activeWordOn: true,
      activeWordColor: '#FFE600',
      activeWordScale: 1.2,
    }
  },
];
